### ISSUE TITLE
Could Not Retrieve Global Preferences

### ISSUE THREAD

**Issue by carharv** [Yooooomi/your_spotify#100]
When I go to the client web page I the error "Could Not Retrieve Global Preferences" pops up. I click the login link and everything seems like its working properly on Spotify's end, but nothing shows up when I get redirected back. 

I have tried clearing my browser cache, using incognito, and switching browsers. Any help would be appreciated, thanks!

This is my compose file:
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8085:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.0.171:8085 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://192.168.0.171:8086
      - SPOTIFY_PUBLIC=_PUBLIC_
      - SPOTIFY_SECRET=_SECRET_
      - CORS=http://192.168.0.171:5000,http://192.168.0.171:5001 # all if you want to allow every origin
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "8086:3000"
    environment:
      - API_ENDPOINT=http://192.168.0.171:8085
```

<img width="749" alt="Screen Shot 2022-03-06 at 3 46 03 PM" src="https://user-images.githubusercontent.com/61243088/156941582-d1195305-c74e-4e9c-a8c4-c99ee471fd26.png">
