### ISSUE TITLE
Issues logging in

### ISSUE THREAD

**Issue by ling-nyc** [Yooooomi/your_spotify#105]
When I click login, it redirects me to `https://spotify.example.com/api/oauth/spotify` which returns `Cannot GET /api/oauth/spotify`.
My docker:
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotify.example.com/api # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://spotify.example.com
      - SPOTIFY_PUBLIC=
      - SPOTIFY_SECRET=
      - CORS=all # all if you want to allow every origin
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=https://spotify.example.com/api
```

My caddyfile:
```
spotify.example.com {
	reverse_proxy localhost:3000
	reverse_proxy /api/* localhost:8080
}
```
