### ISSUE TITLE
Apache2 reverse proxy

### ISSUE THREAD

**Issue by Siphor3on** [Yooooomi/your_spotify#112]
Hi, I got your_spotify running in docker, now I want to make the server accesable from outside. The problem is I get no error on the webpage but I also can't login (when I click the login button it just disappeares and nothing is happening)

This is my docker config:
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotify.website.de # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=https://spotify.website.de
      - SPOTIFY_PUBLIC=****
      - SPOTIFY_SECRET=****
      - CORS=all # all if you want to allow every origin
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=https://spotify.website.de
 ```

Apache2 config
```
<VirtualHost *:80>
ServerAlias spotify.website.de
RewriteEngine On
RewriteCond %{SERVER_NAME} =spotify.website.de
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
</VirtualHost>


<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerAlias spotify.website.de
    SSLProxyEngine On
    ProxyPass /api http://192.168.5.11:8080/
    ProxyPassReverse /api http://192.168.5.11:8080/


    ProxyPass / http://192.168.5.11:3000/
    ProxyPassReverse / http://192.168.5.11:3000/


    <IfModule mod_headers.c>
    Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains>
    </IfModule>

    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
    ProxyRequests Off


    SSLCertificateFile /etc/letsencrypt/live/spotify.website.de/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/spotify.website.de/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf

</VirtualHost>
</IfModule>
```

Do you have any ideas?
Thank you

**Comment by joshbouy** [comment]
I'm currently trying to do the same thing too but for some reason my login redirects to localhost and not where I setup my api endpoint to be. Idk if you're getting the same issue if you check your console

**Comment by Yooooomi** [comment]
Hello!
Can I ask you to provide me your callback url you set in the Spotify dashboard?
Also, I don't know much of Apache, but why is your virtual host on :80 when you try to use ssl that uses port 443? Maybe I'm wrong on this :)

**Comment by Siphor3on** [comment]
Hi,
callback url is https://spotify.website.de/oauth/spotify/callback at the moment

the :80 block is for redirection to https

**Comment by D4rkPh0en1x** [comment]
You define your proxy_pass for the api as /api but as api_endpoint you don't have that at the end
for me the api_endpoint should be https://spotify.website.de/api with your config
an so the callback url also needs this /api/

**Comment by Siphor3on** [comment]
Now I get the error "Cannot GET //oauth/spotify" when I try to login.. I changed both API Endpoint in the yml.. What am I doing wrong?

**Comment by Siphor3on** [comment]
It looks the same

**Comment by Yooooomi** [comment]
Yes, you only log with Spotify now! I'm glad you got it working! Feel free to close if you don't have issues anymore :)

**Comment by D4rkPh0en1x** [comment]
@Siphor3on I‘m very curious to know what the issue was at the end :)
Can you tell me/us?

**Comment by Siphor3on** [comment]
These are the configs that are working now.

Docker file:
`version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotify.website.de/api # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=https://spotify.website.de
      - SPOTIFY_PUBLIC=****
      - SPOTIFY_SECRET=****
      - CORS=all # all if you want to allow every origin
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    restart: always
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=https://spotify.website.de/api`

Apache2 Proxy
`<VirtualHost *:80>
ServerAlias spotify.website.de
RewriteEngine On
RewriteCond %{SERVER_NAME} =spotify.website.de
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
</VirtualHost>


<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerAlias spotify.website.de
    SSLProxyEngine On
    ProxyPass /api/ http://INTERNAL_IP:8080/
    ProxyPassReverse /api/ http://INTERNAL_IP:8080/


    ProxyPass / http://INTERNAL_IP:3000/
    ProxyPassReverse / http://INTERNAL_IP:3000/


    <IfModule mod_headers.c>
    Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains; preload"
    </IfModule>

    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
    ProxyRequests Off


    SSLCertificateFile /etc/letsencrypt/live/spotify.website.de/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/spotify.website.de/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf

</VirtualHost>
</IfModule>`


Spotify Redirect URIs
`https://spotify.brueggy.de/api/oauth/spotify/callback`

**Comment by Siphor3on** [comment]
These are the configs that are working now. Thank you very much for your help!

Docker file:
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotify.website.de/api
      - CLIENT_ENDPOINT=https://spotify.website.de
      - SPOTIFY_PUBLIC=****
      - SPOTIFY_SECRET=****
      - CORS=all # all if you want to allow every origin
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    restart: always
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=https://spotify.website.de/api
```

Apache2 Reverse Proxy:
```
<VirtualHost *:80>
ServerAlias spotify.website.de
RewriteEngine On
RewriteCond %{SERVER_NAME} =spotify.website.de
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
</VirtualHost>


<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerAlias spotify.website.de
    SSLProxyEngine On
    ProxyPass /api/ http://INTERNAL_IP:8080/
    ProxyPassReverse /api/ http://INTERNAL_IP:8080/


    ProxyPass / http://INTERNAL_IP:3000/
    ProxyPassReverse / http://INTERNAL_IP:3000/


    <IfModule mod_headers.c>
    Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains; preload"
    </IfModule>

    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
    ProxyRequests Off


    SSLCertificateFile /etc/letsencrypt/live/spotify.website.de/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/spotify.website.de/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf

</VirtualHost>
</IfModule>
```


Spotify Redirect URIs
```
https://spotify.website.de/api/oauth/spotify/callback
```
