### ISSUE TITLE
Error message: Could not retrieve all the registered accounts (/accounts returns 401)

### ISSUE THREAD

**Issue by CaptaiNiveau** [Yooooomi/your_spotify#133]
**Describe the bug**
When I open the website, I get the error message **Could not retrieve all the registered accounts** (see below in screenshots), unless I logged in previously in the browser session.

**Expected behavior**
No error message if I haven't logged on yet and staying logged in if I was logged in in a previous session.

**Additional context**
In the debugger window is a 401 unauthorized response from the backend for /backend/accounts (I set the base path to /backend), everything else works. Looking into the logs of the server docker, the 401 response shows up there as well.

I tried to ease the CORS setting and set it to all, however that didn't help either.

I'm using Swag with NGINX as a reverse proxy between Cloudflare and my server.

Here is my compose file: (notice there aren't any port mappings, since I'm proxying directly to the container from the swag container, inside the docker network)

```yaml
services:
  backend:
    container_name: yourspotify-backend
    image: yooooomi/your_spotify_server
    networks:
      swag:
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://my.domain/backend # This MUST be included as a valid URL in the spotify dashboard (see below)
      - CLIENT_ENDPOINT=https://my.domain
      - SPOTIFY_PUBLIC=asdfasdfasdf
      - SPOTIFY_SECRET=fdsafdsafdsa
      - CORS=all # https://my.domain # commented out the domain here, but that didn't help
  mongo:
    container_name: yourspotify-mongo
    image: mongo:4.4.8
    networks:
      swag:
    volumes:
      - /mnt/user/appdata/yourspotify/mongo:/data/db

  web:
    container_name: yourspotify-frontend
    image: yooooomi/your_spotify_client
    networks:
      swag:
    restart: always
    environment:
      - API_ENDPOINT=https://my.domain/backend
      
networks:
  swag:
    external: true
```

This is the nginx configuration:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name spotify.*;

    include /config/nginx/ssl.conf;

    location /backend {
        return 301 $scheme://$host/backend/;
    }

    location /backend/ {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app yourspotify-backend;
        set $upstream_port 8080;
        set $upstream_proto http;
        rewrite /backend(.*) $1 break;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app yourspotify-frontend;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

As I said, it all works after logging in with my own account. It doesn't work for anybody else though.

**Screenshots**
![image](https://user-images.githubusercontent.com/79282544/169887347-8a7d0ba0-8d90-46d0-9fc4-5de62c4b8ae0.png)

![image](https://user-images.githubusercontent.com/79282544/169888435-eefbbfdd-9e19-4331-8342-288b92376300.png)
