### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by entropiccode** [Yooooomi/your_spotify#137]
**Describe the bug**

Open the site, click on "Login with Spotify".  502 error received on redirect.

**Expected behavior**

Redirected to Spotify login authorization page.

**Additional context**

Installed via docker-compose, using the provided docker-compose.yml example file.  Hosted on an internal network utilizing internal domain names via DNS rewrites (provided by AdGuard Home).  Using self-signed certificates for https.  The main page loads without issue, problem occurs when attempting to login to spotify to auth.

_docker-compose.yml_
```yaml
version: "3.4"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "30003:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://internal.domain/api # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=https://internal.domain
      - SPOTIFY_PUBLIC=[redacted]
      - SPOTIFY_SECRET= [redacted]
      - CORS=all # all if you want to allow every origin
      - TIMEZONE=America/Denver
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "30002:3000"
    environment:
      - API_ENDPOINT=https://internal.domain/api
```
_nginx site config_
```nginx
server {
	server_name			internal.domain;
	listen				443 ssl;

	# SSL
	ssl_certificate		[redacted];
	ssl_certificate_key	[redacted];
        ssl_protocols		TLSv1.2;

	ssl_session_cache	shared:SSL:1m;
	ssl_session_timeout	5m;

	# logging
	error_log			[redacted]/error.log warn;

	location /	{
		proxy_pass              http://localhost:30002/;
	}

    location /api/	{
		proxy_pass              http://localhost:30003/;
	}
}

server {
	if ($host = internal.domain) {
		return 301 https://internal.domain$request_uri;
	}
		listen 80 ;
		listen [::]:80;
	server_name internal.domain;
	return 404;
}
```
_Spotify Application Redirect URIs_
```
https://internal.domain/api/oauth/spotify/callback
https://internal.domain/oauth/spotify/callback
```

_Nginx error log output_
```
2022/06/10 17:11:15 [error] 431986#431986: *73 upstream prematurely closed connection while reading response header from upstream, client: 10.7.7.211, server: internal.domain, request: "GET /api/oauth/spotify/callback?code=<snip code> HTTP/1.1", upstream: "http://127.0.0.1:30003/oauth/spotify/callback?code=<snip code>", host: "internal.domain", referrer: "https://internal.domain/"
```

_Container Logs_
```
myspotify-server-1  | 2022-06-10T16:13:12.079268720Z yarn run v1.22.18
myspotify-server-1  | 2022-06-10T16:13:12.119228397Z $ node ./lib/migrations.js
myspotify-server-1  | 2022-06-10T16:13:12.584828507Z [info]  Trying to connect to database at mongodb://mongo:27017/your_spotify  
myspotify-server-1  | 2022-06-10T16:13:12.633182313Z [info]  Connected to database !
myspotify-server-1  | 2022-06-10T16:13:12.720865204Z [info]  Starting migrations
myspotify-server-1  | 2022-06-10T16:13:12.721353736Z [info]  Migrations successfully ran
myspotify-server-1  | 2022-06-10T16:13:12.726913218Z Done in 0.66s.
myspotify-server-1  | 2022-06-10T16:13:12.941979312Z yarn run v1.22.18
myspotify-server-1  | 2022-06-10T16:13:12.979604291Z $ node lib/bin/www
myspotify-server-1  | 2022-06-10T16:13:13.652199028Z [info]  Trying to connect to database at mongodb://mongo:27017/your_spotify  
myspotify-server-1  | 2022-06-10T16:13:13.699818049Z [info]  Connected to database !
myspotify-server-1  | 2022-06-10T16:13:13.705024546Z [info]  Checking database...
myspotify-server-1  | 2022-06-10T16:13:13.752146215Z [warn]  No user is admin, cannot auto fix database
myspotify-server-1  | 2022-06-10T16:13:13.778589200Z [info]  Starting loop for 0 users
myspotify-server-1  | 2022-06-10T16:13:19.984282306Z GET /me 304 8.346 ms - -
myspotify-server-1  | 2022-06-10T16:13:20.014098848Z GET /global/preferences 304 11.997 ms - -
myspotify-server-1  | 2022-06-10T16:13:21.385536544Z GET /me 304 1.480 ms - -
myspotify-server-1  | 2022-06-10T16:13:21.407306052Z GET /global/preferences 304 5.659 ms - -
myspotify-server-1  | 2022-06-10T16:13:23.160755181Z GET /oauth/spotify 302 8.334 ms - 628
myspotify-server-1  | 2022-06-10T16:13:23.580816086Z node:internal/process/promises:279
myspotify-server-1  | 2022-06-10T16:13:23.580851143Z             triggerUncaughtException(err, true /* fromPromise */);
myspotify-server-1  | 2022-06-10T16:13:23.580860972Z             ^
myspotify-server-1  | 2022-06-10T16:13:23.580868185Z
myspotify-server-1  | 2022-06-10T16:13:23.580874436Z [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 400".] {
myspotify-server-1  | 2022-06-10T16:13:23.580884322Z   code: 'ERR_UNHANDLED_REJECTION'
myspotify-server-1  | 2022-06-10T16:13:23.580888375Z }
myspotify-server-1  | 2022-06-10T16:13:23.609152129Z error Command failed with exit code 1.
myspotify-server-1  | 2022-06-10T16:13:23.609298478Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Unsure what the exact issue is here, I've tried rewrites for the /api/ block and increasing proxy timeouts in the nginx config with no changes, so my assumption is that the connection is being interrupted by the your_spotify process itself because of the error shown in the container logs.
