### ISSUE TITLE
Issues with Importing

### ISSUE THREAD

**Issue by entropiccode** [Yooooomi/your_spotify#138]
**Describe the bug**

Two distinct issues I noticed when importing my prior year privacy data:

~~1. Certain files won't import, with the import button doing nothing when those files are chosen to be imported, whether alone or in a group.~~
2. When importing a single file, a progress bar appears for the import, then progress stays at 0.

**Expected behavior**

~~1. Chosen files are imported, with a progress bar appearing when the "Import" button is clicked.~~
2. Interface updates properly to reflect progress on the import

**Additional context**

_docker-compose.yml_
```yml
version: "3.4"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "30003:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://internal.domain/api # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=https://internal.domain
      - SPOTIFY_PUBLIC=[redacted]
      - SPOTIFY_SECRET=[redacted]
      - CORS=all # all if you want to allow every origin
      - TIMEZONE=America/Denver
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "30002:3000"
    environment:
      - API_ENDPOINT=https://internal.domain/api
```

~~Issue 1:
The first issue appears to be related to file size?  I have two StreamingHistoryX.json files, with StreamingHistory0.json failing to import with a filesize of 1362 KB, and StreamingHistory1.json importing successfully with a file size of 393 KB.
I cannot find anything in the logs indicating the server or client registering that I am clicking the import button.
The import section tells me "Everything looks fine for the import to work", so I do not believe it is a formatting issue.~~

Issue 2:
My second file, StreamingHistory1.json, did import successfully.  However, the progress bar for the import never updated, staying at 0/2808 until I refreshed and saw it had completed.
The logs showed that the import was happening, and all of the data appears to have imported without issue now that it is complete.
