### ISSUE TITLE
Using y_s behing nginx proxy manager- localhost:8080 error

### ISSUE THREAD

**Issue by tjohnson-2** [Yooooomi/your_spotify#141]
First off, I'm doing all of this through Portainer on a remote, headless server. I've configured the Docker CE script to point to two different URLs: https://spotify... (port 3000) and https://spotifyauth... (port 8080. I've added these ports to Cloudflare as I use that for my DNS. Upon visiting *spotify... and clicking the "Login with Spotify" button, it takes a second to load but then serves the page http://localhost:8080/oauth/spotify. This shouldn't be happening because I've changed all of the references to http://localhost:8080/ to point to https://spotifyauth...

Expected behavior:

Was expecing the home page to load as it does when the exact same config if used, just with all of the localhost URLs instead of the NPM URLs.

Additional context:

- compose file:
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotify...
      - CLIENT_ENDPOINT=https://spotifyauth...
      - SPOTIFY_PUBLIC=**************************************
      - SPOTIFY_SECRET=**************************************
      - CORS=all # all if you want to allow every origin
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=https://spotifyauth...
```

Screenshots

[https://imgur.com/a/DvpyOLm](url)

**Comment by LennartKoziollek** [comment]
Hello, i seem to have the same error.
Im hosting everything behind nginx proxy manager. Im constantly getting redirected to localhost:8080 when trying to authenticate myself.

```
docker-compose:
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://auth.example.com# This MUST be included as a valid URL in the spotify dashboard (see below)
      - CLIENT_ENDPOINT=http://localhost:3000
      - SPOTIFY_PUBLIC=***
      - SPOTIFY_SECRET=***
      - CORS=http://localhost:3000,http://localhost:3001 # all if you want to allow every origin
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    environment:
      - API_ENDPOINT=http://auth.example.com
```

My Nginx has works with the webservice but not with the localhost:8080 it seems. I redirect the auth.example.com url to http://yourspotify-server-1:8080

Maybe you can help me aswell
