### ISSUE TITLE
"Last year" shows incomplete listening history

### ISSUE THREAD

**Issue by lluni** [Yooooomi/your_spotify#143]
**Describe the bug**

The option "Last year" doesn't completely show the last year of listening history but shows February as empty and cuts off somewhere in March even though February and March (and also all the months later) have plays (cf. screenshots).

**Expected behavior**

The option "Last year" shows the last year of listening history.

**Additional context**

```YAML
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    networks:
      - your_spotify
      - npm_bridge
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://sapi.domain.com # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=https://spotify.domain.com
      - SPOTIFY_PUBLIC=[redacted]
      - SPOTIFY_SECRET=[redacted]
      - CORS=all # all if you want to allow every origin
      - MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - your_spotify

  web:
    image: yooooomi/your_spotify_client
    restart: always
    networks:
      - your_spotify
      - npm_bridge
    environment:
      - API_ENDPOINT=https://sapi.domain.com

networks:
    your_spotify:
        external: false
    npm_bridge:
        external: true
```
Exported the last 1000 lines of log with Portainer: [your_spotify_server_logs.txt](https://github.com/Yooooomi/your_spotify/files/9011641/your_spotify_server_logs.txt)

**Screenshots**
"Last year"
![last_year](https://user-images.githubusercontent.com/36239317/176464632-9268755a-f758-425a-9978-bb6901b0df31.png)

"Feb 1, 2022 - Feb 28, 2022"
![Feb](https://user-images.githubusercontent.com/36239317/176464802-02edfc36-7abd-425b-92d0-36bcd7bdadc6.png)

"Mar 1, 2022 - Mar 31, 2022"
![Mar](https://user-images.githubusercontent.com/36239317/176466682-02b77627-764c-4712-b3c5-4aa7b25750ee.png)
