### ISSUE TITLE
Crashes when calling backend

### ISSUE THREAD

**Issue by s0ftcorn** [Yooooomi/your_spotify#144]
First time setting this up, knowing a few things about docker, reverse proxies, etc.
Whenver i go to https://spotifyauth.NOPE.de/oauth/spotify/callback i get:
```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server
```

And in the logs:

```
server_1  | [warn]  No user is admin, cannot auto fix database
mongo_spotify | {"t":{"$date":"2022-07-03T00:25:19.098+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.30.0.4:53506","connectionId":39,"connectionCount":6}}
mongo_spotify | {"t":{"$date":"2022-07-03T00:25:19.100+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn39","msg":"client metadata","attr":{"remote":"172.30.0.4:53506","client":"conn39","doc":{"driver":{"name":"nodejs|Mongoose","version":"4.5.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.0-20-amd64"},"platform":"Node.js v16.15.0, LE (unified)","version":"4.5.0|6.3.2"}}}
mongo_spotify | {"t":{"$date":"2022-07-03T00:25:19.110+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.30.0.4:53508","connectionId":40,"connectionCount":7}}
mongo_spotify | {"t":{"$date":"2022-07-03T00:25:19.112+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn40","msg":"client metadata","attr":{"remote":"172.30.0.4:53508","client":"conn40","doc":{"driver":{"name":"nodejs|Mongoose","version":"4.5.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.0-20-amd64"},"platform":"Node.js v16.15.0, LE (unified)","version":"4.5.0|6.3.2"}}}
server_1  | [info]  Starting loop for 0 users
mongo_spotify | {"t":{"$date":"2022-07-03T00:25:25.146+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1656807925:146336][1:0x7f1dc62df700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 3, snapshot max: 3 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 19"}}
server_1  | node:internal/process/promises:279
server_1  |             triggerUncaughtException(err, true /* fromPromise */);
server_1  |             ^
server_1  | 
server_1  | [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 400".] {
server_1  |   code: 'ERR_UNHANDLED_REJECTION'
server_1  | }
mongo_spotify | {"t":{"$date":"2022-07-03T00:25:27.298+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn39","msg":"Connection ended","attr":{"remote":"172.30.0.4:53506","connectionId":39,"connectionCount":5}}
mongo_spotify | {"t":{"$date":"2022-07-03T00:25:27.298+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn36","msg":"Connection ended","attr":{"remote":"172.30.0.4:53500","connectionId":36,"connectionCount":2}}
mongo_spotify | {"t":{"$date":"2022-07-03T00:25:27.298+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn35","msg":"Connection ended","attr":{"remote":"172.30.0.4:53498","connectionId":35,"connectionCount":1}}
mongo_spotify | {"t":{"$date":"2022-07-03T00:25:27.298+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn38","msg":"Connection ended","attr":{"remote":"172.30.0.4:53504","connectionId":38,"connectionCount":6}}
mongo_spotify | {"t":{"$date":"2022-07-03T00:25:27.298+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn37","msg":"Connection ended","attr":{"remote":"172.30.0.4:53502","connectionId":37,"connectionCount":4}}
mongo_spotify | {"t":{"$date":"2022-07-03T00:25:27.298+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn40","msg":"Connection ended","attr":{"remote":"172.30.0.4:53508","connectionId":40,"connectionCount":3}}
mongo_spotify | {"t":{"$date":"2022-07-03T00:25:27.299+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn34","msg":"Interrupted operation as its client disconnected","attr":{"opId":827}}
mongo_spotify | {"t":{"$date":"2022-07-03T00:25:27.301+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn34","msg":"Connection ended","attr":{"remote":"172.30.0.4:53496","connectionId":34,"connectionCount":0}}
server_1  | error Command failed with exit code 1.
server_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
your_spotify_server_1 exited with code 1
```

What i thought was going on is the warning about no admin, but since there is no user, i guess i makes sense and is expected upon first time setup.

My docker-compose.yml:
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://spotifyauth.NOPE.de # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://spotify.NOPE.de
      - SPOTIFY_PUBLIC=NOPE
      - SPOTIFY_SECRET=NOPE
      - CORS=http://localhost:3000,http://localhost:3001 # i have no idea what this does lol
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify

  mongo:
    container_name: mongo_spotify
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://spotifyauth.NOPE.de
```

Im running this behind a basic apache reverse proxy:
```
<VirtualHost *:80>
        ServerName spotifyauth.NOPE.de
        Redirect permanent / https://spotify.NOPE.de/
</VirtualHost>
<VirtualHost *:443>
ServerName spotifyauth.NOPE.de

SSLEngine On
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/NOPE.de-0001/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/NOPE.de-0001/privkey.pem
ProxyPreserveHost On

RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}
ProxyPass / http://127.0.0.1:8080/
ProxyPassReverse / http://127.0.0.1:8080/

ErrorLog ${APACHE_LOG_DIR}/spotify-error.log
CustomLog ${APACHE_LOG_DIR}/spotify-access.log combined

</VirtualHost>
```
Config for web looks basically the same only domain and port changed.
Any idea whats going on?
