### ISSUE TITLE
Service sons

### ISSUE THREAD

**Issue by Trrw** [Yooooomi/your_spotify#145]
Hello, unfortunately the service does not start properly for me. When opening the IP http://192.168.178.156:3000, "Could not retrieve global preferences" appears. 

When I start the service in the terminal like this: 

```
cd yourspotify
docker-compose up
```

the service opens and works. After restarting Ubuntu, the service starts, but "Could not retrieve global preferences" appears. When I press login, the message "ERR_CONNECTION_REFUSED" appears in the browser.

docker-compose.yml 
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.178.156:8080 # This MUST be included as a valid URL in the spotify dashboard (see below)
      - CLIENT_ENDPOINT=http://192.168.178.156:3000
      - SPOTIFY_PUBLIC=XXXXXXXXXXXXXXXXXXXX
      - SPOTIFY_SECRET=XXXXXXXXXXXXXXXXXXXX
      - CORS=http://localhost:3000,http://localhost:3001 # all if you want to allow every origin
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://192.168.178.156:8080

```

Redirect URIs
```
http://192.168.178.156:3000/oauth/spotify/callback
http://192.168.178.156:8080/oauth/spotify/callback
```
