### ISSUE TITLE
Could not retrieve global preferences Error

### ISSUE THREAD

**Issue by TheBoxManer** [Yooooomi/your_spotify#146]
Hey, I have deployed this in docker (Using a Raspberry Pi 4) and it works for abit, then randomly stops working and gives me the error "Could not retrieve global preferences". When I clear my cache it works again for abit but then does the same thing.

![image](https://user-images.githubusercontent.com/108699005/177219101-7495c315-0251-4f69-96c7-db349a11fbde.png)

```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: unless-stopped
    ports:
      - "3081:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.1.78:3081
      - CLIENT_ENDPOINT=http://192.168.1.78:3080
      - SPOTIFY_PUBLIC=removed
      - SPOTIFY_SECRET=removed
      - CORS=http://192.168.1.78:3080
      - TIMEZONE=Europe/London
  mongo:
    container_name: mongo-your-spotify
    image: mongo:4.4.8
    volumes:
      - /portainer/Files/AppData/Config/your_spotify/DB:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3080:3000"
    environment:
      - API_ENDPOINT=http://192.168.1.78:3081
```

**Comment by Yooooomi** [comment]
Hello! 
The error you are encountering is explained in the screenshot you shared. You are having an extra headers that is not allowed by cors policy.
It is closely related to #32

**Comment by EthanCoster** [comment]
Oh okay then, sorry I'm quite new to this. Is there any way to include that extra header somewhere to fix the error from happening? Because clearing my cache & cookies fixes it for a small amount of time before it starts erroring again.

**Comment by Yooooomi** [comment]
What services are you hosting? And to which of them you log in?

**Comment by Yooooomi** [comment]
Maybe you could remove headers with a special nginx config. I never did that. I'll take a look

**Comment by Yooooomi** [comment]
Can you try something like this https://stackoverflow.com/questions/44536548/how-to-remove-client-headers-in-nginx-before-passing-request-to-upstream-server with the x-xsrf-token for the your_spotify configuration.

**Comment by slhx99** [comment]
Same issue here, is there any way to provide it with a DNS so that I can tell it to bypass my pihole's DNS?

**Comment by Yooooomi** [comment]
@slhx99 i think this issue is not related to dns. Only headers being set when they should not be.

**Comment by slhx99** [comment]
oh, alright, any idea how to work around it? i don't quite understand the x-xsrf-token thing either

**Comment by Yooooomi** [comment]
Hello, any news on this one?

**Comment by slhx99** [comment]
Hi! I've just been deleting cookies whenever the error pops up, other than that, it's working fine

**Comment by makanimike** [comment]
I have been struggling with this error too. 
I can get it to work sometimes after many many reloads and cookie deletes (say ballpark area of 20 attempts to 1 success). I even removed all other services/apps I had on that VM and it now exclusively runs Your Spotify. But that didn't change the success rate at all. 
I don't understand removing headers with nginx or pihole right now. That is something I would have to learn more about down the line, after I get a somewhat foundation of services up and running stably. 

(on a side note, and I am not sure if that is perhaps another symptom of the same issue, but the few times I do get Your Spotify to work, any reload required me to hit the "Login with Spotify" button again)

**Comment by Yooooomi** [comment]
Hello @makanimike, is the header name the same as in the original issue description? Can you post a screenshot of the browser error please? (The one in the console)

**Comment by makanimike** [comment]
slightly different, it seems. I get an Axios error, too, but the rest looks a bit different.

<img width="1188" alt="Capture" src="https://user-images.githubusercontent.com/88232673/207594896-0e6e0038-d253-4b20-aea0-3b422c17aaa8.PNG">

**Comment by Yooooomi** [comment]
@makanimike this is not the same issue. Please open an issue if you're still having trouble. It seems that you can't connect to your backend from your computer here.

**Comment by makanimike** [comment]
ok. I will troubleshoot some more. strange though, because I get the same behavior from inside the VM that is running Your Spotify. anyway....let me collect some more data.

**Comment by makanimike** [comment]
I think I fixed mine. I had missed to change one port reference in the sample docker-compose.yml. strange that it would occasionally work.  This seems to have also fixed having to login to spotify every time I reload the page.

**Comment by vordenken** [comment]
I'm currently having the same issue(s). 
Sometimes connecting works, sometimes it doesn't.
Here's my compose.yml:

```

version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.178.4:8080 # This MUST be included as a valid URL in the spotify dashboard (see below)
      - CLIENT_ENDPOINT=http://192.168.178.4:3001
      # ENV Variables
      - SPOTIFY_PUBLIC=$SPOTIFY_PUBLIC
      - SPOTIFY_SECRET=$SPOTIFY_SECRET
      - CORS=http://192.168.178.4:3001 # all if you want to allow every origin
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - /docker/your_spotify_db/:/data/db
    restart: unless-stopped

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3001:3000"
    environment:
      - API_ENDPOINT=http://192.168.178.4:8080
    labels:
     - homepage.group=Container
     - homepage.name=your_spotify
     - homepage.href=http://192.168.178.4:3001
 
```

And a screenshot of the error messages from my browser:
![Bildschirm­foto 2023-01-11 um 12 23 55](https://user-images.githubusercontent.com/62395860/211794897-9ba5be19-c80e-470f-a155-17632c2dc328.png)
