### ISSUE TITLE
Issue with Logging In

### ISSUE THREAD

**Issue by DarkKronicle** [Yooooomi/your_spotify#148]
Hello! I'm having some trouble getting logging in to work. 

Here is my current docker compose setup for the project:

```YML
  spotify-server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8888:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://myspotify.DOMAIN.com/api
      - CLIENT_ENDPOINT=https://myspotify.DOMAIN.com
      - SPOTIFY_PUBLIC=XXXXXXXXXX
      - SPOTIFY_SECRET=XXXXXXXXXX
      - CORS=all # All for testing purposes
      
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  spotify-client:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3333:3000"
    environment:
      - API_ENDPOINT=https://myspotify.DOMAIN.com/api
 ```
 
 Connecting to both `authmyspotify` and `myspotify` works. When connecting to `myspotify` and I click `Log In`, it goes to `https://myspotify.DOMAIN.com/oauth/spotify` and shows a blank dashboard. If I change the URL to `https://myspotify.DOMAIN.com/api/oauth/spotify` I'm able to authorize, but it then redirects me back to `https://myspotify.DOMAIN.com/login`. Looking at the logs of the server, it looks like it correctly logs me in, it's just the front end that doesn't log in correctly.

Screenshot of after clicking log in:
![image](https://user-images.githubusercontent.com/38167691/182434183-40b0b5d4-47f1-4218-b430-cf238f063286.png)

Thanks for the help!

**Comment by DarkKronicle** [comment]
Ok, so I got it to work, though I am still very confused.

After messing with it for a while, I realized that `API_ENDPOINT` wasn't carried over in the front-end, even though in the console it said it was. I looked at environment variables, and it was all set, but the login button and other endpoints wouldn't go to the correct URL. Randomly after a reset (even though I did it many times) it fixed itself. I don't know if it was because a container was removed or something, or if something was cached weird. I changed it to `myspotify.DOMAIN.com/api` but then it went to `authmyspotify.DOMAIN.com` which was what was set before.

Works now, so I don't mind, but mainly just confused now lol.

**Comment by Yooooomi** [comment]
Hello, sorry for not reaching to you sooner. Is your issue resolved?

**Comment by Dhruvgera** [comment]
Hi, I am having the exact same issue. Is there any definite solution other than pure luck?

**Comment by Dhruvgera** [comment]
> Hello, sorry for not reaching to you sooner. Is your issue resolved?

I am having the exact same issue, any fix for this?

**Comment by Dhruvgera** [comment]
> @Dhruvgera hello. I can't help you without any configuration files.

```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://spotify.xxx.app/api
      - CLIENT_ENDPOINT=http://spotify.xxx.app
      - SPOTIFY_PUBLIC=
      - SPOTIFY_SECRET=
      - CORS=all
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    restart: always
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://spotify.xxx.app/api
```

This is my config, and I am having the same issue as @DarkKronicle did. The sign up works, but the blank black screen happens
