### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by chrisg991** [Yooooomi/your_spotify#149]
I've recently updated Your Spotify and have suddenly started getting this error when logging in "INVALID_CLIENT: Invalid redirect URI".

I've tried changing the URIs on the Spotify dashboard to all possible combinations of different things to get it working but still no luck, and I'm not sure what I've got wrong. Please would someone help me work it out?

My reverse proxy settings are as follows:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/26568742/183246388-64c6efdf-1de3-4b63-88bb-661ba66d01ad.png">

<img width="490" alt="image" src="https://user-images.githubusercontent.com/26568742/183246418-3ba44f6a-ebb6-40a4-8073-5f2a4861fee5.png">

The frontend can be accessed successfully at http://yourspotify.lan and was (presumably) able to access http://yourspotify.lan/api correctly as the app was working before the update. 

My docker-compose file is as follows (please ignore all the comments - these are previous unsuccessful changes)
```
version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: express-mongo
    restart: always
    build: ./server
    ports:
#host:container
      - "8181:8080"
   # links:
     # - mongo
   # depends_on:
    #  - mongo
    environment:
      - API_ENDPOINT=http://yourspotify.lan/api/
#      - API_ENDPOINT=http://192.168.3.100:8181 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://yourspotify.lan
#      - CLIENT_ENDPOINT=http://192.168.3.100:3000
      - SPOTIFY_PUBLIC=REDACTED
      - SPOTIFY_SECRET=REDACTED
     # - CORS=http://192.168.2.3:3000,http://192.168.2.100:3001
      - CORS=http://192.168.3.100:3000,http://192.168.3.100:3001,http://yourspotify.lan,http://yourspotify.lan/api/
      - CORS=all
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
  mongo:
    container_name: mongo_spotify
    image: mongo:4.4.10
    volumes:
     - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: web
    restart: always
    #build: ./client
    ports:
      - "3000:3000"
    environment:
#      - API_ENDPOINT=http://192.168.3.100:8181
      - API_ENDPOINT=http://yourspotify.lan/api/
```

And my Spotify Developer Dashboard is as follows:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/26568742/183246531-eeb349d6-4b45-41e2-a362-2410b2ad9d48.png">

I must have a setting wrong somewhere but I'm not sure where?
