### ISSUE TITLE
Could not retrive global prefrences error after trying to change the ip adresses to domains with NPM

### ISSUE THREAD

**Issue by trbntwo** [Yooooomi/your_spotify#155]
Hello,
I wanted to make Your_Spotify reachable outside my home network, so I made the IP of the web interface reachable via my reverse proxy (NGINX Proxy Manager) (ys.mydomain.com). However, then you can't be authenticated outside the home network, so I changed the API_ENDPOINT to the domain api.ys.mydomain.com and assigned the respective ports via the reverse proxy. Then I also updated the forwarding URI in the Spotify dashboard.

However, I get the "Could not retrive global prefrences" error and end up in a login loop, when I press login and log in I am redirected back to the login page and then it loops

Same Problem is also in Private Tab, Chromium based Browsers and WebKit based Browsers

My docker-compose file:
```
version: '3'

services:

  YourSpotify-Server:
    image: yooooomi/your_spotify_server
    container_name: YourSpotify-Server
    hostname: YourSpotify-Server
    restart: unless-stopped
    ports:
      - '8062:8080'
    links:
      - MongoDB-YS
    depends_on:
      - MongoDB-YS
    environment:
      - API_ENDPOINT=http://api.ys.mydomain.com # This MUST be included as a valid URL in the spotify dashboard (see below)
      - CLIENT_ENDPOINT=http://local-ip:port # reverse proxy gives domain
      - SPOTIFY_PUBLIC=X
      - SPOTIFY_SECRET=X
      - CORS=all
      - TIMEZONE=Europe/Berlin
      - MONGO_ENDPOINT=mongodb://MongoDB-YS:27017/your_spotify

  MongoDB-YS:
    image: mongo:4.4.8
    container_name: MongoDB-YS
    hostname: MongoDB-YS
    restart: unless-stopped
    volumes:
      - /home/Docker/YourSpotify:/data/db

  YourSpotify-Web:
    image: yooooomi/your_spotify_client
    container_name: YourSpotify-Web
    hostname: YourSpotify-Web
    restart: unless-stopped
    ports:
      - '8012:3000'
    environment:
      - API_ENDPOINT=http://api.ys.mydomain.com

```
