### ISSUE TITLE
"Hello !" response from /oauth/spotify

### ISSUE THREAD

**Issue by tmeuze** [Yooooomi/your_spotify#158]
**Describe the bug**

Hi, thanks for the project!

I have Your Spotify behind Traefik. I've figured out path rewriting, and am not experiencing the "could not retrieve preferences" error anymore. However, when I click _login_ and get directed to `/oauth/spotify`, I just get a "Hello !" response in the browser. 

**Expected behavior**

Redirect to Spotify authentication

**Additional context**

`docker-compose.yml`:
<spoiler><details>
```
version: "3"

services:
  app:
    container_name: ys_app
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "9812:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://ys.domain.tld/api
      - CLIENT_ENDPOINT=http://ys.domain.tld
      - SPOTIFY_PUBLIC=[redacted]
      - SPOTIFY_SECRET=[redacted]
      - CORS=all # all if you want to allow every origin
      - TIMEZONE=America/New_York
      - LOG_LEVEL=debug
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./db:/data/db
  web:
    container_name: ys_web
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "9813:3000"
    environment:
      - API_ENDPOINT=https://ys.domain.tld/api
```
</details></spoiler>

Traefik:

<spoiler><details>
```
http:
  middlewares:
    replaceRoot:
      replacePath:
        path: "/"
```

```
http:
  routers:

# Your-Spotify
    ys.domain.tld:
      entryPoints:
        - websecure
      middlewares:
        - secureRedir@file
        - secureHeaders@file
      tls:
        certResolver: lecf
      rule: Host(`ys.domain.tld`)
      service: your-spotify

    ys.domain.tld-api:
      entryPoints:
        - websecure
      middlewares:
        - secureRedir@file
        - secureHeaders@file
        - replaceRoot
      tls:
        certResolver: lecf
      rule: Host(`ys.domain.tld`) && PathPrefix(`/api`)
      service: your-spotify-api
```
</details></spoiler>

No errors in log. Just what appears to be successful requests:
`2022-09-27T18:56:43.916799743Z GET / 200 0.379 ms - 7`

**Screenshots**

![CleanShot 2022-09-27 at 15 02 50](https://user-images.githubusercontent.com/9298659/192613504-a5a5e9e0-a568-4e42-b0f9-f8feef6b886a.png)

![CleanShot 2022-09-27 at 15 03 32](https://user-images.githubusercontent.com/9298659/192613565-4889e483-a1c7-4ce2-9dbd-ebbb073c4dad.png)

![CleanShot 2022-09-27 at 15 09 54](https://user-images.githubusercontent.com/9298659/192614799-6bd92f64-9e4e-44a7-86b6-4ea4a48ce071.png)

Thanks for your help!
