### ISSUE TITLE
Some assistance with setup needed.

### ISSUE THREAD

**Issue by athphane** [Yooooomi/your_spotify#16]
Hi! I've been trying to set the project up for myself and I'm stuck. I've set up the docker-compose file and nginx as follows:

### docker-compose.yml
``` yaml
version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: express-mongo
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://spotify.domain.com/api
      - CLIENT_ENDPOINT=http://spotify.domain.com
      - SPOTIFY_PUBLIC=redacted
      - SPOTIFY_SECRET=redacted
      - CORS=all

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /home/titan/your_spotify/db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://spotify.domain.com/api
```

### spotify.domain.com nginx conf file
``` conf
server {
  listen 80;
  server_name spotify.domain.com;

  location / {
    proxy_pass http://localhost:3000/;
  }

  location /api {
    proxy_pass http://localhost:8080/;
  }
}
```

With this much, I am able to get to the login page of the app when i go to http://spotify.domain.com like below. 

![image](https://user-images.githubusercontent.com/13810742/94870968-4b34f500-0462-11eb-9ed2-cc0b32a6465e.png)

On this same page, I get a 404 error. It's trying to go to /api/me
![image](https://user-images.githubusercontent.com/13810742/94871060-8800ec00-0462-11eb-9488-45cf50d24109.png)

When I try to register, I get this:
![image](https://user-images.githubusercontent.com/13810742/94871197-e29a4800-0462-11eb-9670-b6e4e322e025.png)

I read through some of the issues and they helped me get here. Any extra help is appreciated.
