### ISSUE TITLE
Time Mismatch

### ISSUE THREAD

**Issue by NeoHBz** [Yooooomi/your_spotify#169]
**Describe the bug**

While I listen to songs on Spotify, the "Your History > Listened At" section reports correct timing at while I played the song, however, the graph on "Time Listened" isn't accurate, it offsets by a period of 4-5 hours usually.

**Expected behavior**

If I am playing a song at 23:00, the "Time Listened" graph should draw the line at the 23:00 period.

**Additional context**

#### docker-compose.yml
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotifyserver.mytld.com
      - CLIENT_ENDPOINT=https://spotifystats.mytld.com
      - SPOTIFY_PUBLIC=mypublic
      - SPOTIFY_SECRET=mysecret
      - CORS=all # all if you want to allow every origin
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=https://spotifyserver.mytld.com
```

**Screenshots**

Image showing songs have been played at 23:00 to 00:00 time period
<img width="1440" alt="Screenshot 2022-11-25 at 11 50 10 PM" src="https://user-images.githubusercontent.com/56602090/204038799-c0920819-6a0b-44fc-86c6-448ec651fae9.png">

Image showing the graph has instead drawn at 18:00 hours
<img width="762" alt="Screenshot 2022-11-25 at 11 50 36 PM" src="https://user-images.githubusercontent.com/56602090/204038947-49b9d502-c705-4c9b-81b3-c0df91214597.png">

**Shared link**
My Shared Link: https://myspotify.neohbz.com

**Comment by Yooooomi** [comment]
Hello. Sad to see that. Do you live in a particular time zone different from Paris? Does changing it accordingly to the readme solves the problem?

**Comment by NeoHBz** [comment]
> Hello. Sad to see that. Do you live in a particular time zone different from Paris? Does changing it accordingly to the readme solves the problem?

I am embarrassed for not reading the README thoroughly and missing out on the default TIMEZONE value, and yes, changing it according to the readme solves my problem. Thank you.

For anyone visiting this in future, you need to add **TIMEZONE** environment variable in your docker-compose (or whichever way you're running). My new config looks like this:

docker-compose.yml
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotifyserver.mytld.com
      - CLIENT_ENDPOINT=https://spotifystats.mytld.com
      - SPOTIFY_PUBLIC=mypublic
      - SPOTIFY_SECRET=mysecret
      - CORS=all # all if you want to allow every origin
      - TIMEZONE=Asia/Kolkata                                   # ADDED THIS
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=https://spotifyserver.mytld.com
```
