### ISSUE TITLE
Importing JSON from Spotify is super slow.

### ISSUE THREAD

**Issue by shanff** [Yooooomi/your_spotify#171]
**Describe the bug**

Importing JSON data from spotify is sloooooooow

**Expected behavior**

Importing data should be far quicker

**Additional context**

```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard (see below)
      - CLIENT_ENDPOINT=http://localhost:3000
      - SPOTIFY_PUBLIC=xxxx
      - SPOTIFY_SECRET=xxxx
      - CORS=http://localhost:3000,http://localhost:3001 # all if you want to allow every origin
  mongo:
    restart: always
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://localhost:8080
```

**Screenshots**
5 minutes after start of import.  I have 2 more files to import as well.
Import of 19:44 fromfull-privacy
In progress (3788/15669)

**Shared link**

It's not shared out to the internet.

As a comparison test, I created a quick Python script that imports the entirety of my full history files into a SQLite3 database and it takes less than 3 seconds for all 33k records.

```
import json
import sqlite3

conn = sqlite3.connect('spotify_database.db')
spt_json1 = json.load(open('endsong_0.json'))
spt_json2 = json.load(open('endsong_1.json'))
spt_json3 = json.load(open('endsong_2.json'))

for batch in [spt_json1, spt_json2, spt_json3]:
    columns = []
    column = []
    for data in batch:
        column = list(data.keys())
        for col in column:
            if col not in columns:
                columns.append(col)


    values = []
    value = []
    for data in batch:
        for i in columns:
            value.append(str(dict(data).get(i)))
        values.append(list(value))
        value.clear()

    create_query = 'create table if not exists table_songs(ts, \
                                                        username, \
                                                        platform, \
                                                        ms_played, \
                                                        conn_country, \
                                                        ip_addr_decrypted, \
                                                        user_agent_decrypted, \
                                                        master_metadata_track_name, \
                                                        master_metadata_album_artist_name, \
                                                        master_metadata_album_album_name, \
                                                        spotify_track_uri, \
                                                        episode_name, \
                                                        episode_show_name, \
                                                        spotify_episode_uri, \
                                                        reason_start, \
                                                        reason_end, \
                                                        shuffle, \
                                                        skipped, \
                                                        offline, \
                                                        offline_timestamp, \
                                                        incognito_mode)'

    insert_query = 'insert into table_songs values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)'
    c = conn.cursor()
    c.execute(create_query)
    c.executemany(insert_query,values)
    conn.commit()
    ```

[19:58:25]  time python json_import.py

real	0m0.599s
user	0m0.490s
sys	0m0.045s

sqlite> select count(*) from table_songs;
33743
