### ISSUE TITLE
Could not retrieve global preferences - Reason: CORS header ‘Access-Control-Allow-Origin’ missing

### ISSUE THREAD

**Issue by c0pper** [Yooooomi/your_spotify#176]
Both when the login page loads and after login attempt "Could not retrieve global preferences" error pops up.
I've read the other issues regarding this notification but haven't found one with the same error as in my logs.
Here's my stack:

```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "4288:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.1.151:4288 # This MUST be included as a valid URL in the spotify dashboard (see below)
      - CLIENT_ENDPOINT=http://192.168.1.151:3000
      - SPOTIFY_PUBLIC=client id
      - SPOTIFY_SECRET=client secret
      - CORS=http://192.168.1.151:3000,http://192.168.1.151:3002 # all if you want to allow every origin
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - /home/pi/docker/configs/your_spotify/db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://192.168.1.151:4288
```

I tries with firefox both in incognito and normally, and with Chrome. Screenshots:

Firefox:
![image](https://user-images.githubusercontent.com/18085925/207116484-4e2e15b6-26c3-4c15-962d-529e6a7e60c1.png)

Fresh install of Chrome:
![image](https://user-images.githubusercontent.com/18085925/207116259-7523d862-04f6-4092-a59c-a0b8d3829476.png)

Thanks for the software and for your time.
