### ISSUE TITLE
Problems with the login procedure

### ISSUE THREAD

**Issue by MattTheDrago** [Yooooomi/your_spotify#177]
Hi, I am having some trouble to access the auth webpage

Here is my docker-compose file

```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    container_name: server_spotify
    restart: always
    ports:
      - "8484:8484"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.1.20:8484/ # This MUST be included as a valid URL in the spotify dashboard (see below)
      - CLIENT_ENDPOINT=http://192.168.1.20:3000
      - SPOTIFY_PUBLIC=${Client_ID}
      - SPOTIFY_SECRET=${Client_secret}
      - CORS=http://192.168.1.20:3000,http://192.168.1.20:3001 # all if you want to allow every origin
  mongo:
    container_name: mongo_spotify
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: web_spotify
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://192.168.1.20:8484
```

I made sure that all the ports are open to ufw, and from the container logs it looks like everything is working. Once I connect to the main dashbord and click on the login button I get redirected to `http://192.168.1.20:8484/oauth/spotify` and I get this. 

![image](https://user-images.githubusercontent.com/64641684/208372496-73ec8743-7586-4b00-a38d-f3cf94e4b6c4.png)

I tried looking through already submitted issues but I couldn't find anything similar to this
