### ISSUE TITLE
Web UI doesn't point to API_ENDPOINT

### ISSUE THREAD

**Issue by KenHV** [Yooooomi/your_spotify#186]
The link in web UI points to localhost:8080/oauth/spotify or an older URL I used for API_ENDPOINT.

I'm able to authenticate by manually going to API_ENDPOINT/oauth/spotify, but it makes no difference to the web UI.

Logs say this: `ys-web     | Setting API Endpoint to 'https://ys.kenharris.xyz/api'` but the link is either localhost:8080 or ys.kenharris.xyz/backend (the old URL).

I have tried stopping/starting/deleting/pruning. I've tried with different browsers, different devices and with incognito mode as well. Clearing cache doesn't help. I've also tried `delete window.API_ENDPOINT` as someone in another issue had success with it. Purging Cloudflare cache has no effect either.

[Docker logs.](https://github.com/Yooooomi/your_spotify/files/10429577/logs.txt)

Config:
```
version: "3"

services:
  ys-server:
    container_name: ys-server
    image: yooooomi/your_spotify_server
    restart: always
    links:
      - ys-mongo
    depends_on:
      - ys-mongo
    environment:
      - API_ENDPOINT=https://ys.kenharris.xyz/api # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=https://ys.kenharris.xyz
      - SPOTIFY_PUBLIC=
      - SPOTIFY_SECRET=
      - CORS=all # all if you want to allow every origin
    # Port 8080
    networks:
      - default
      - npm

  ys-mongo:
    container_name: mongo
    image: mongo:4.4.8
    restart: always
    volumes:
      - ./your_spotify_db:/data/db

  ys-web:
    container_name: ys-web
    image: yooooomi/your_spotify_client
    restart: always
    environment:
      - API_ENDPOINT=https://ys.kenharris.xyz/api
    # Port 3000
    networks:
      - default
      - npm

networks:
  npm:
    external: true
```
