### ISSUE TITLE
Browser doesn't store access token during login process

### ISSUE THREAD

**Issue by math625f** [Yooooomi/your_spotify#187]
# Describe the bug

Hi there, I just booted up Your Spotify in a dockerized environment, but I'm unable to log in. Clicking the log in button in the client redirects me back to the same page, where I can log in again.
- I tried changing the URL in Spotify Dashboard, but by doing so I'm greeted by an error page on Spotify.
- I tried setting CORS=all but to no avail.
- When inspecting the requests in my browser, I can clearly tell that it is trying to log me in. On the ` http://spotapi.munken/oauth/spotify/callback` request (response 302) my browser is receiving a `Set-Cookie` header with what appears to be a JWT token. This token is **not** stored as a cookie by my browser, and even when I set the cookie manually named `token`, the browser does **not** use the token for further requests (i.e. it sends the request `http://spotapi.munken/me?token=` and get response `{"status":false}`), If I manually copy paste the token and send the above request to the API with token included, I get some data back from the API. 
- As can be seen in the logs, the backend application must have registered that I have logged in, due to the fact that it's processing songs.
- My main browser is Vivaldi, but I have tried in Chrome and Edge as well, no success. I have disabled ad blockers, that did not work either.
- Note that my endpoints are purely internal, and that I'm using a custom setup where all `*.munken` requests are forwarded to my local server.

# Expected behavior

That my browser will store the token received from the server, and allow me to log in.

# Additional context

## Compose:
```yaml
version: "3"

services:
  server:
    container_name: spotify_server
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - 59627:8080
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://spotapi.munken # This MUST be included as a valid URL in the spotify dashboard (see below)
      - CLIENT_ENDPOINT=http://spotify.munken
      - SPOTIFY_PUBLIC=xxx
      - SPOTIFY_SECRET=xxx
      - CORS=all
      - TZ=Europe/Copenhagen
    restart: unless-stopped

  mongo:
    container_name: spotify_mongo
    image: mongo:4.4.8
    volumes:
      - /home/munken/docker/spotify:/data/db
    restart: unless-stopped
    environment: 
      - TZ=Europe/Copenhagen

  web:
    image: yooooomi/your_spotify_client
    container_name: spotify_client
    restart: unless-stopped
    ports:
      - 59628:3000
    environment:
      - API_ENDPOINT=http://spotapi.munken
      - TZ=Europe/Copenhagen
```

## Server logs during login:

![image](https://user-images.githubusercontent.com/22494364/212911643-1bcd7643-9cab-441a-af85-1e477d35c53f.png)

You can see that I've attempted to login multiple times, and the responses by the server _seem_ to be correct.

I'm sure that I'm probably overlooking something obvious in my configuration, and I hope someone will be able to assist me in this problem.
