### ISSUE TITLE
It says "Could not retrieve global preferences", when I now go to login into my Spotify

### ISSUE THREAD

**Issue by nath2125** [Yooooomi/your_spotify#190]
**Describe the bug**

It says "Could not retrieve global preferences", when I now go to login into my Spotify. I have everything linked and mongo DB running also and restarted all 3 containers it creates in the stack in my portainer and I'm having the same issues.

I am also running this in portainer as said above. 

**Expected behaviour**

Normally this doesn't happen and I have been running it now for a month and it works every time. Today I tried it after not looking at it for a few days and it came up with this.

**My Compose**

```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8085:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.10.7:8085 # This MUST be included as a valid URL in the spotify dashboard (see below)
      - CLIENT_ENDPOINT=http://192.168.10.7:8086
      - SPOTIFY_PUBLIC=(takenout)
      - SPOTIFY_SECRET=(takenout)
      - CORS=http://192.168.10.7:3000,http://192.168.10.7:3001,http://192.168.10.7:8086 # all if you want to allow every origin
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "8086:3000"
    environment:
      - API_ENDPOINT=http://192.168.10.7:8085
```

**Screenshots**

![image](https://user-images.githubusercontent.com/99367069/213922855-29f5d2af-a8a4-43b2-8ffd-a4d11e8daa65.png)

![image](https://user-images.githubusercontent.com/99367069/213922877-73cdb0e3-e239-4a8f-b4af-a508bbf06db7.png)

If there is more required let me know. I'm not to sure what I'm looking for which is why I have given as much as I can think of here
