### ISSUE TITLE
Facing "MongooseServerSelectionError: connection timed out"

### ISSUE THREAD

**Issue by NeoHBz** [Yooooomi/your_spotify#195]
**Describe the bug**

The server, runs into "MongooseServerSelectionError: connection timed out" error while starting up

Logs:
```
GET /me?token= 200 2.363 ms - 16
GET /oauth/spotify 302 3.836 ms - 730
/app/node_modules/mongoose/lib/model.js:5214
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: connection timed out
    at Function.Model.$wrapCallback (/app/node_modules/mongoose/lib/model.js:5214:32)
    at /app/node_modules/mongoose/lib/query.js:4908:21
    at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at model.Query.exec (/app/node_modules/mongoose/lib/query.js:4907:10)
    at model.Query.Query.then (/app/node_modules/mongoose/lib/query.js:4990:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: TopologyDescription {
    type: 'Single',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 4284639488,
        lastWriteDate: 0,
        error: MongoNetworkTimeoutError: connection timed out
            at connectionFailureError (/app/node_modules/mongodb/lib/cmap/connect.js:389:20)
            at Socket.<anonymous> (/app/node_modules/mongodb/lib/cmap/connect.js:310:22)
            at Object.onceWrapper (node:events:627:28)
            at Socket.emit (node:events:513:28)
            at Socket._onTimeout (node:net:550:8)
            at listOnTimeout (node:internal/timers:559:17)
            at processTimers (node:internal/timers:502:7) {
          [Symbol(errorLabels)]: Set(0) {}
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Setting CORS to 'all' is not needed anymore, omitting it is the new way of authorizing every origin.
yarn run v1.22.19
$ node ./lib/migrations.js
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
```

**Additional context**
```
❯ docker image ls
REPOSITORY                        TAG       IMAGE ID       CREATED         SIZE
yooooomi/your_spotify_client      latest    0ba2f1438453   6 days ago      134MB
yooooomi/your_spotify_server      latest    83e3aa6c51b4   6 days ago      635MB
```
docker-compose.yml
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotifyserver.mywebsite.com
      - CLIENT_ENDPOINT=https://spotify.mywebsite.com
      - SPOTIFY_PUBLIC=
      - SPOTIFY_SECRET=
      - CORS=all # all if you want to allow every origin
      - TIMEZONE=Asia/Kolkata                                   # ADDED THIS
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=https://spotifyserver.mywebsite.com

```
