### ISSUE TITLE
Can't import fulll privacy: Wrongly formatted file

### ISSUE THREAD

**Issue by xinput** [Yooooomi/your_spotify#201]
**Describe the bug**

Hello, Today I received my full privacy data from spotify, unfortunately I'm not able to import them into yourspotify as I'm always getting an error that import initialization failed and the format might be wrong.

**Expected behavior**
import should start as it does for the normal privacy

**Additional context**

Here's the used docker compose:

<details>
  <summary>docker_compose.yml</summary>

  ```

version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://server.srv:8080 # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: http://server.srv:3000
      SPOTIFY_PUBLIC: my_public_token
      SPOTIFY_SECRET: my_secret_token
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://server.srv:8080

```
</details>

and here are the logs

<details>
  <summary>Logs</summary>

```

  {

      code: 'invalid_type',

      expected: 'string',

      received: 'null',

      path: [Array],

      message: 'Expected string, received null'

    },

    ... 2283 more items

  ]

}

[error]  TypeError: Cannot read properties of null (reading 'length')

    at FullPrivacyImporter.<anonymous> (/app/lib/tools/importers/full_privacy.js:105:51)

    at Generator.next (<anonymous>)

    at fulfilled (/app/lib/tools/importers/full_privacy.js:5:58)

```
</details>

not sure if spotify changed something since this importer was implemented but here's the syntax spotify provided inside the full privacy export about the syntax used in endsong.json

```

{
"ts": "YYY-MM-DD 13:30:30",
"username": "_________",
"platform": "_________",
"ms_played": _________,
"conn_country": "_________",
"ip_addr_decrypted": "___.___.___.___",
"user_agent_decrypted": "_________",
"master_metadata_track_name": "_________,
“master_metadata_album_artist_name:_________”,
“master_metadata_album_album_name:_________",
“spotify_track_uri:_________”,
"episode_name": _________,
"episode_show_name": _________,
“spotify_episode_uri:_________”,
"reason_start": "_________",
"reason_end": "_________",
"shuffle": null/true/false,
"skipped": null/true/false,
"offline": null/true/false,
"offline_timestamp": _________,
"incognito_mode": null/true/false
}

```
