### ISSUE TITLE
The web application can't communicate with the server error 

### ISSUE THREAD

**Issue by jamess60** [Yooooomi/your_spotify#208]
**Describe the bug**

When deploying the app via the template docker compose file (and inputting my details), the webpage launches but gives a red error bar saying "The web application can't communicate with the server". When clicking login with spotify, it redirects to the API Endpoint address but 404's.

**Expected behavior**

I would not see the "The web application can't communicate with the server" error and clicking login with spotify would take me to the sign in page. 

**Additional context**

Docker compose exert:
ip is the local IPV4 address of the docker host 
```
    your_spotify_server:
        container_name: your_spotify_server
        image: yooooomi/your_spotify_server
        ports:
            - "8080:8080"
        restart: always
        links:
            - mongo_your_spotify_server
        depends_on:
            - mongo_your_spotify_server
        environment:
            API_ENDPOINT: http://ip.ip.ip.ip:8080
            CLIENT_ENDPOINT: http://ip.ip.ip.ip:3000
            SPOTIFY_PUBLIC: $key
            SPOTIFY_SECRET: $key
            TIMEZONE: Europe/London
            CORS: all #debug
    mongo_your_spotify_server:
        container_name: mongo_your_spotify_server
        image: mongo:4.4.8
        volumes:
            - /containerstorage/your_spotify_server/data:/data/db
    your_spotify_server_client:
        container_name: your_spotify_server_client
        image: yooooomi/your_spotify_client
        restart: always
        ports:
            - "3000:3000"
        environment:
            API_ENDPOINT: http://ip.ip.ip.ip:8080
```

Have added localhost and the ipv4 variants of the oauth link to the spotify app 

**Screenshots**
 
Not applicable 

**Shared link**
Unable to provide, cant sign in
