### ISSUE TITLE
Cannot login 

### ISSUE THREAD

**Issue by Jayy001** [Yooooomi/your_spotify#222]
**Describe the bug**

When I go to login, the `/callback` just returns `ERR_CONNECTION_REFUSED`

**Expected behavior**

To be able to login

**Additional context**

```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8070:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://192.168.0.137:8070 # This MUST be included as a valid URL in the spotify dashboard
      CLIENT_ENDPOINT: http://192.168.0.137:3000
      SPOTIFY_PUBLIC: xyz
      SPOTIFY_SECRET: xyz
      CORS: all # "all" if you want to allow every origin

  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - /mnt/storage/data/spotify:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://192.168.0.137:8070
```
```
Setting API Endpoint to 'http://192.168.0.137:8070'
 WARN  Checking for updates failed (use `--debug` to see full error)
 INFO  Accepting connections at http://0.0.0.0:3000
 HTTP  4/8/2023 3:07:02 PM 192.168.0.135 GET /
 HTTP  4/8/2023 3:07:02 PM 192.168.0.135 Returned 304 in 57 ms
 HTTP  4/8/2023 3:07:02 PM 192.168.0.135 GET /variables.js
 HTTP  4/8/2023 3:07:02 PM 192.168.0.135 GET /static/js/main.bf85c65a.js
 HTTP  4/8/2023 3:07:02 PM 192.168.0.135 Returned 304 in 6 ms
 HTTP  4/8/2023 3:07:02 PM 192.168.0.135 GET /static/css/main.7a14ab5f.css
 HTTP  4/8/2023 3:07:02 PM 192.168.0.135 Returned 304 in 5 ms
 HTTP  4/8/2023 3:07:02 PM 192.168.0.135 Returned 304 in 16 ms
 HTTP  4/8/2023 3:07:13 PM 192.168.0.135 GET /static/css/main.7a14ab5f.css
 HTTP  4/8/2023 3:07:13 PM 192.168.0.135 Returned 304 in 4 ms
 HTTP  4/8/2023 3:07:13 PM 192.168.0.135 GET /manifest.json
 HTTP  4/8/2023 3:07:13 PM 192.168.0.135 Returned 304 in 3 ms
 HTTP  4/8/2023 3:07:14 PM 192.168.0.135 GET /static/js/main.bf85c65a.js.map
 HTTP  4/8/2023 3:07:14 PM 192.168.0.135 Returned 200 in 39 ms
 HTTP  4/8/2023 3:07:14 PM 192.168.0.135 GET /static/css/main.7a14ab5f.css.map
 HTTP  4/8/2023 3:07:14 PM 192.168.0.135 Returned 200 in 6 ms
 HTTP  4/8/2023 3:07:27 PM 192.168.0.135 GET /login
 HTTP  4/8/2023 3:07:27 PM 192.168.0.135 Returned 304 in 3 ms
 HTTP  4/8/2023 3:07:27 PM 192.168.0.135 GET /variables.js
 HTTP  4/8/2023 3:07:27 PM 192.168.0.135 Returned 304 in 2 ms
 HTTP  4/8/2023 3:07:27 PM 192.168.0.135 GET /static/css/main.7a14ab5f.css
 HTTP  4/8/2023 3:07:27 PM 192.168.0.135 GET /static/js/main.bf85c65a.js
 HTTP  4/8/2023 3:07:27 PM 192.168.0.135 Returned 304 in 2 ms
 HTTP  4/8/2023 3:07:27 PM 192.168.0.135 Returned 304 in 2 ms
 HTTP  4/8/2023 3:07:27 PM 192.168.0.135 GET /static/css/main.7a14ab5f.css.map
 HTTP  4/8/2023 3:07:27 PM 192.168.0.135 Returned 200 in 2 ms
 HTTP  4/8/2023 3:07:28 PM 192.168.0.135 GET /static/js/main.bf85c65a.js.map
 HTTP  4/8/2023 3:07:28 PM 192.168.0.135 Returned 200 in 2 ms
 HTTP  4/8/2023 3:07:28 PM 192.168.0.135 GET /favicon.ico
 HTTP  4/8/2023 3:07:28 PM 192.168.0.135 Returned 304 in 3 ms
 HTTP  4/8/2023 3:07:29 PM 192.168.0.135 GET /static/css/main.7a14ab5f.css
 HTTP  4/8/2023 3:07:29 PM 192.168.0.135 Returned 304 in 2 ms
 HTTP  4/8/2023 3:07:29 PM 192.168.0.135 GET /manifest.json
 HTTP  4/8/2023 3:07:29 PM 192.168.0.135 Returned 304 in 1 ms
 HTTP  4/8/2023 3:08:45 PM 192.168.0.135 GET /
 HTTP  4/8/2023 3:08:45 PM 192.168.0.135 Returned 200 in 2 ms
 HTTP  4/8/2023 3:08:45 PM 192.168.0.135 GET /favicon.ico
 HTTP  4/8/2023 3:08:45 PM 192.168.0.135 Returned 200 in 2 ms
 HTTP  4/8/2023 3:08:45 PM 192.168.0.135 GET /variables.js
 HTTP  4/8/2023 3:08:45 PM 192.168.0.135 GET /static/js/main.bf85c65a.js
 HTTP  4/8/2023 3:08:45 PM 192.168.0.135 Returned 200 in 3 ms
 HTTP  4/8/2023 3:08:45 PM 192.168.0.135 Returned 200 in 3 ms
 HTTP  4/8/2023 3:08:45 PM 192.168.0.135 GET /static/css/main.7a14ab5f.css
 HTTP  4/8/2023 3:08:45 PM 192.168.0.135 Returned 200 in 2 ms
 HTTP  4/8/2023 3:08:45 PM 192.168.0.135 GET /favicon.ico
 HTTP  4/8/2023 3:08:45 PM 192.168.0.135 Returned 200 in 1 ms
 HTTP  4/8/2023 3:08:45 PM 192.168.0.135 GET /favicon.ico
 HTTP  4/8/2023 3:08:45 PM 192.168.0.135 Returned 304 in 2 ms
 HTTP  4/8/2023 3:09:53 PM 192.168.0.135 GET /static/css/main.7a14ab5f.css.map
 HTTP  4/8/2023 3:09:53 PM 192.168.0.135 Returned 200 in 2 ms
 HTTP  4/8/2023 3:09:53 PM 192.168.0.135 GET /static/js/main.bf85c65a.js.map
 HTTP  4/8/2023 3:09:53 PM 192.168.0.135 Returned 200 in 5 ms
```
```
$ node lib/bin/www
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
[info]  Connected to database !
[info]  Checking database...
[info]  Starting loop for 1 users
[info]  Refreshing songs for Jake
```

**Screenshots**
![image](https://user-images.githubusercontent.com/56607897/230728819-e91d75f8-4e2f-42e5-b123-b2d15b491bae.png)
![image](https://user-images.githubusercontent.com/56607897/230728969-0e030bbd-d68f-44ba-89e2-af3ab7df3ff9.png)

**Shared link**

If you don't mind, you can add a Shared link to this issue by clicking **Share this page** on your YourSpotify application so that I can identify the issue quicker.

![image](https://user-images.githubusercontent.com/56607897/230729005-0e5af473-be89-44f4-b363-7471d461f8e2.png)

I had no issues with it earlier, was working fine perfectly - just tried it today and it refuses to work...no helpful logs either that I was able to use
