### ISSUE TITLE
Issues with setup

### ISSUE THREAD

**Issue by Brulijam** [Yooooomi/your_spotify#234]
Hi,
I am using this docker compose setup
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://spotify.domain.com/api/
      CLIENT_ENDPOINT: https://spotify.domain.com/
      SPOTIFY_PUBLIC: abc123
      SPOTIFY_SECRET: abc123
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - /var/docker/your_spotify/db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: https://spotify.domain.com/api/
```
and nginx proxy manager where `spotify.domain.com` proxies to `172.18.0.1:3000` and `spotify.domain.com/api` to `172.18.0.1:8080`.

The redirect uri in the spotify app dashboard is set to `https://spotify.domain.com/api/oauth/spotify/callback`.

When opening `spotify.domain.com` I get the Error `The web application can't communicate with the server` and the login button redirects to `http://localhost:8884/oauth/spotify`.

Not sure what I am missing.
