### ISSUE TITLE
Import seems to fail

### ISSUE THREAD

**Issue by rondDev** [Yooooomi/your_spotify#239]
**Describe the bug**

I am not aware if this is a bug or not, but it does seem like unwanted behavior. It seems as if I can't recover from it on my own.

I am faced with "Failed and cleaned", but I can't seem to figure out how to recover from it.

**Expected behavior**

Import isn't supposed to fail, but it did. Another user had a successful import right after mine failed.

**Additional context**

```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8181:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://redacted# This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: https://redacted
      SPOTIFY_PUBLIC: dd5f7ae532e44e9885f93953093628e4
      SPOTIFY_SECRET: 8b8bb4b7c1fb4b99b1af0473d73e8d49
      CORS: all
  mongo:
    container_name: mongo
    image: mongo:4.4.18
    volumes:
      - /var/lib/docker/volumes/yourspot/_data:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "8282:3000"
    environment:
      API_ENDPOINT: https://redacted 
```

[All logs](https://gist.github.com/rondDev/6e66730ad16010af74e8ad0e75a4da20)

**Screenshots**

![](https://rond.cc/u/aKzhqrSI5oal.png)
![](https://rond.cc/u/nLwU18AXgQnE.png)
