### ISSUE TITLE
Issues Again

### ISSUE THREAD

**Issue by mcrummett** [Yooooomi/your_spotify#241]
After spending ages getting this working it has stopped again.  I have tried removing the docker container(s) and rebuilding but alas.

It fails to connect to the mongo database.  i am using the following docker-compose.yml

```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://192.168.1.111:8080 # This MUST be included as a valid URL in the spotify dashboard
      CLIENT_ENDPOINT: http://192.168.1.111:3000
      SPOTIFY_PUBLIC: REDACTED
      SPOTIFY_SECRET: REDACTED
      CORS: http://192.168.1.111:3000,http://192.168.1.111:3001 # "all" if you want to allow every origin

  mongo:
    container_name: mongo
    image: mongo:5
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://192.168.1.111:8080
```
