### ISSUE TITLE
MongoDB Atlas Free tier not working on 1.6.0

### ISSUE THREAD

**Issue by byzocker** [Yooooomi/your_spotify#242]
**Describe the bug**

Trying to use MongoDB's Free Atlas Database results after updating to 1.6.0 results in these logs and the server container failing to start up

```
yarn run v1.22.19
$ node ./lib/migrations.js
[info]  Trying to connect to database at mongodb+srv://{}.mongodb.net/
[info]  Connected to database !
/app/node_modules/mongodb/lib/cmap/connection.js:201
                    callback(new error_1.MongoServerError(document));
                             ^
MongoServerError: {getParameter: 1, featureCompatibilityVersion: ""} not allowed in this atlas tier
    at Connection.onMessage (/app/node_modules/mongodb/lib/cmap/connection.js:201:30)
    at MessageStream.<anonymous> (/app/node_modules/mongodb/lib/cmap/connection.js:59:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:124:16)
    at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at MessageStream.Writable.write (node:internal/streams/writable:336:10)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)
    at TLSSocket.emit (node:events:513:28) {
  ok: 0,
  code: 8000,
  codeName: 'AtlasError',
  [Symbol(errorLabels)]: Set(0) {}
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**

Normal startup like in previous versions

**Additional context**

my docker compose:
```
version: "3"
services:

  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_ENDPOINT: mongodb+srv://{}.mongodb.net/?retryWrites=true&w=majority
      API_ENDPOINT: https://api.spotify.domain.com
      CLIENT_ENDPOINT: https://spotify.domain.com
      SPOTIFY_PUBLIC: public key
      SPOTIFY_SECRET: secret key

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: https://api.spotify.domain.com
```
