### ISSUE TITLE
Your_Spotify + Cloudflare Tunnel

### ISSUE THREAD

**Issue by Worldrazor** [Yooooomi/your_spotify#243]
Hello! First of all, this is a really cool application! 

I'm trying to use Cloudflare Tunnels to get this up and running on my website, and unfortunately I'm hitting some issues. I have the login page and I can login, but when I get to the dashboard it's just blank. I can't press anything. I will here give you my config: 

![spotifysd](https://github.com/Yooooomi/your_spotify/assets/102300756/12f53e6d-6b84-4a2c-9695-c3c8931bc97e)

Docker: 
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://spotify.domain # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: https://spotify-api.domain.com
      SPOTIFY_PUBLIC: 
      SPOTIFY_SECRET: 
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: https://spotify-api.domain.com
```

Cloudflare: 
![cloudflare](https://github.com/Yooooomi/your_spotify/assets/102300756/06efbff6-899c-4137-b79d-31daee6414c6)

Spotify: 
![spotify](https://github.com/Yooooomi/your_spotify/assets/102300756/62c3ac96-0240-4c8b-878c-fa03b02c4987)

When I'm at the dashboard I get this url: 

`https://spotify.domain.com/oauth/spotify/callback?code=AQDCZUI2bqgM0UM-dPBS6H5WkbFIKzWT-q9ln_BQ_gJuWxTFFYE7aPEtzPIwBcLcpREoSaeSZ8GncHAk8rnlBAiYvtujDypwDzr3KvgsDusS3GKEh9DVbpubBApnzCfjtYxpQDcMNrD8QFHXiknZV-2vuKGl_duztpE4i5NM-kyJV9yiLU7FgHkvgN8vd60E5CTXr-fZz2VixIcLBvuH83S3gHZQfHhUOHkvDPefBNnFWJnvrUmUtIJOi-wGnMokH6FIEx-qLV6DbYKXxhMnnfYIvG_5Fs-7F8hcgU6cKPEYaxTw5BdUgBHMJW6uftwgNzYvcx5Szf0xG8DcZd2TVrHZmvKslw-F3m-Lrdjd21JgzFiEEpUKiB9YIYoK2f-M6f4uwg`

Where am I doing something wrong? It worked great when I just had it on my home network.

Thanks!
