### ISSUE TITLE
Cannot use domain names with reverse proxy

### ISSUE THREAD

**Issue by Thomas-Philippot** [Yooooomi/your_spotify#246]
Hello, I have succesfully installed the app, but when I try to change my local IP addresses with domain names, i get an error on login
(constantly redirected to login page)

My `docker-compose.yml` file :
```yaml
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8000:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://spotify-api.home # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: http://spotify.home
      SPOTIFY_PUBLIC: <private>
      SPOTIFY_SECRET: <private>
  mongo:
    container_name: mongo
    image: mongo:bionic
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://spotify-api.home
```

In nginx proxy manager i added two hosts :

1. `spotify.home` -> wich redirect to my server ip port `3000`
1. `spotify-api.home` -> wich redirect to my server ip port `8000`

Finally on my spotify app the redirect URI is : `http://spotify-api.home/oauth/spotify/callback`

When I access `spotify.home` the frontend loads, but i keep getting redirected to `/login`

The error in console : `GET http://spotify-api.home/version 401 (Unauthorized)`

(I tried adding CORS env var, refreshing browser cache... can't see what is wrong)
