### ISSUE TITLE
Extended streaming history problems

### ISSUE THREAD

**Issue by Worldrazor** [Yooooomi/your_spotify#248]
**Describe the bug**

Can't upload my extended streaming history. It says to use files with starting with `endsongX.json`. I dont have that, so maybe Spotify has changed something? When I try to upload all my year_number.json it dosen't do anything. Just shows the loading sign and then does nothing. I can upload each file 1 by one it seems like.

<img width="603" alt="Screenshot 2023-06-09 at 10 42 27" src="https://github.com/Yooooomi/your_spotify/assets/102300756/e4cf9feb-3ae5-40f0-a3d0-e9655633e183">

<img width="697" alt="Screenshot 2023-06-09 at 10 36 51" src="https://github.com/Yooooomi/your_spotify/assets/102300756/77abc6d9-a361-4c5d-8903-c6a3ed6dcf60">

**Expected behavior**

Upload my files so I can see the statistics. 

**Additional context**

Please paste the docker-compose file you're using to host YourSpotify and their logs (you can skip mongo logs). If your issue have anything related to other tools, please paste their config too.

```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://spotify-api.domain.com # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: https://spotify.domain.com
      SPOTIFY_PUBLIC: 78ca6f8b982a463784fc6a74da0a6c8d
      SPOTIFY_SECRET: a0a7fe6378e44cf990f8cf43fd427438
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: https://spotify-api.domain.com
```
