### ISSUE TITLE
Cannot register

### ISSUE THREAD

**Issue by gclark18** [Yooooomi/your_spotify#25]
When I click register nothing happens and there is no error.

```
version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: express-mongo
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.0.3:3000 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://192.168.0.3:3000
      - SPOTIFY_PUBLIC=0e9c9f0fcb4e417ca559aea00ed7019d
      - SPOTIFY_SECRET=a2298732ecdd4c35a28556728c413c0b
      - CORS=http://192.168.0.3:3000,http://localhost:3001
      - CORS=all
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://localhost:8080
```
