### ISSUE TITLE
Importing Extended Streaming Data not working.

### ISSUE THREAD

**Issue by Supbro112** [Yooooomi/your_spotify#265]
**Describe the bug**
Importing isn't working. I managed to only get one file working and that was 2016-2017 year, it wont take any other files because "import already running on this account" and it says this message even when restarting the server / my system. 

I am also confused because when Spotify sent me my extended streaming history, they are in the format of "Streaming_History_Audio_X" which your_spotify says these should be formatted as "endsongX" so idk what's wrong there, but despite the issue I cannot import any files to either option of importing. It always says an import is running on the account despite trying to restart the server

**Expected behavior**
That your_spotify would take my files all at once and import them all at mass.

**Additional context**

Please paste the docker-compose file you're using to host YourSpotify and their logs (you can skip mongo logs). If your issue have anything related to other tools, please paste their config too.

```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: http://localhost:3000
      SPOTIFY_PUBLIC: 431fd98814e848c6b4a03c24a7d1e547
      SPOTIFY_SECRET: 64707cb2602a47b7ad4d863f5d36186e
      CORS: http://localhost:3000,http://localhost:3001 # "all" if you want to allow every origin
      
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://localhost:8080
```
**Screenshots**
Screenshot of data import area. 
![image_2023-07-22_114851669](https://github.com/Yooooomi/your_spotify/assets/52581779/850f737c-fad1-4fb0-8405-ea529ff9b33e)

Image I made trying to explain the file issues of formatting, and the confusion of which import option is the right one.
![image_2023-07-22_115639180](https://github.com/Yooooomi/your_spotify/assets/52581779/c5793ba9-e2d3-42c1-b14b-c16a6c47e575)

![image_2023-07-22_115731891](https://github.com/Yooooomi/your_spotify/assets/52581779/8d71da13-1d88-441f-bfd2-beaa19116cb8)

Import doesn't recognize new name format
![image_2023-07-22_115754206](https://github.com/Yooooomi/your_spotify/assets/52581779/fd313966-3074-483a-aa56-d4dd298095d9)

**Shared link**
http://localhost:3000/settings/account?gname=Last+day&token=cb675f7a-91a4-4972-8b93-f513d6c7ee05
Dont think it would do much, but hopefully!
