### ISSUE TITLE
CORS issue & not found url

### ISSUE THREAD

**Issue by johnWeak1192** [Yooooomi/your_spotify#27]
Hello, it seems like a really cool project!
I've tried to set up it on my server but I encountered several problems regarding the CORS policy and urls...

Once I try to register, I get this error:
![image](https://user-images.githubusercontent.com/80417424/110674943-ac5fb200-81d2-11eb-997d-d507e5a8421d.png)

Docker compose:
```
version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: express-mongo
    restart: always
    ports:
      - "7000:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://pepega.fun/apispotify # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=https://pepega.fun/spotify
      - SPOTIFY_PUBLIC=edited
      - SPOTIFY_SECRET=edited
      - CORS=all
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: web
    restart: always
    ports:
      - "7002:3000"
    environment:
      - API_ENDPOINT=https://pepega.fun/apispotify
```

Regarding the 404 error I tried the solution mentioned in issue #16  but I gess did not work..

Nginx (edited some line here); 

```
http {

        server {
                server_name pepega.fun www.pepega.fun;
                location /spotify/      { proxy_pass http://localhost:7002/;  }
                location /apispotify    { proxy_pass http://localhost:7000/; rewrite /api/(.*) /$1 break; }

}



                server_name pepega.fun www.pepega.fun;
    listen 80;
    return 404; # managed by Certbot


}}
```

I did enter the call back URL in the Spotify dashboard : 
![image](https://user-images.githubusercontent.com/80417424/110674081-d2d11d80-81d1-11eb-8795-93814225b5c8.png)

Can anyone tell me what I did wrong ? Any tips would be greatly appreciated. 

Thanks !
