### ISSUE TITLE
Working with Cloudflare Tunnel

### ISSUE THREAD

**Issue by hoiber** [Yooooomi/your_spotify#283]
Hey, has anyone had any success using a cloudflare tunnel? Cant seem to get it to work. 

Have tried setting the  API_ENDPOINT: http://serv-spotify.somedomain.xo as recommended in similar issues with reverse proxies (I know cloudflare is different but thought it was worth a go) 

Main issue is the web reports it cant find the server. 

This could be completely not doable but thought someone might have got it working. 

Config Below:

version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8090:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://serv-spotify.somedomain.xo
      CLIENT_ENDPOINT: https://spotify.somedomain.xo
      SPOTIFY_PUBLIC: xxx
      SPOTIFY_SECRET: xxx
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3090:3000"
    environment:
      API_ENDPOINT: https://serv-spotify.somedomain.xo

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=token
    depends_on:
      - web

Cloudflare Settings
<img width="1000" alt="image" src="https://github.com/Yooooomi/your_spotify/assets/51186531/29b1d5d9-bd09-4cd4-9fff-da6b7d6cf5de">

**Comment by arriej** [comment]
Hi, 

Ive been looking at your config and trying to figure out whats wrong with it. So far everything looks like its supposed to work as intended. 
Looking at other cloud-flare issues and domain issues its often caused by cache. So maybe you can clear you cache or try a different browser. 

In my compose config i did include  `[CORS: all](https://github.com/Yooooomi/your_spotify#cors)`  not sure if this is going to fix your issue though.

**Comment by kacperpaluch** [comment]
I have the same problem with Cloudflare.

**Comment by hoiber** [comment]
> Hi,
> 
> Ive been looking at your config and trying to figure out whats wrong with it. So far everything looks like its supposed to work as intended. Looking at other cloud-flare issues and domain issues its often caused by cache. So maybe you can clear you cache or try a different browser.
> 
> In my compose config i did include [CORS: all](https://github.com/Yooooomi/your_spotify#cors) not sure if this is going to fix your issue though.

Thanks, it was indeed the stupid cache!

**Comment by arriej** [comment]
> I have the same problem with Cloudflare.

Hi, just saying u got the same output, but post none of your configs or what U have tried to solve it isn't going to get you on further. 

Show us your docker compose and cloud flare tunnels settings. 
Or try to clear your cache or try a different browser.

**Comment by hkamran80** [comment]
I got Cloudflare Tunnels working with the following Compose file.

```yaml
services:
  server:
    image: yooooomi/your_spotify_server
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      API_ENDPOINT: [server URL]
      CLIENT_ENDPOINT: [client URL]
      SPOTIFY_PUBLIC: [redacted]
      SPOTIFY_SECRET: [redacted]
    restart: always

  mongo:
    image: mongo:6 
    volumes:
      - ./db:/data/db

  web:
    image: yooooomi/your_spotify_client
    depends_on:
      - server
    environment:
      API_ENDPOINT: [server URL]
    restart: always

  web-client:
    image: yooooomi/your_spotify_client
    depends_on:
      - server
    environment:
      API_ENDPOINT: [client URL]
    restart: always

  server-tunnel:
    image: cloudflare/cloudflared:latest
    depends_on:
      - server
    environment:
      TZ: [timezone]
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token [server token]

  web-tunnel:
    image: cloudflare/cloudflared:latest
    depends_on:
      - web-client
    environment:
      TZ: [timezone]
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token [client token]
```
