### ISSUE TITLE
Large time periods do not display entirely

### ISSUE THREAD

**Issue by Jurrer** [Yooooomi/your_spotify#290]
**Describe the bug**

Selecting big data range such as one year, or big custom data range ex. January 1 2023 - Sept 29 2023 displays only months until March 2023(3 months in this particular case).
Calculated time and records seem correct. Error is in Time Listened chart and in most charts in All Stats.

**Expected behavior**

App shows data in requested data range.

**Additional context**

Please paste the docker-compose file you're using to host YourSpotify and their logs (you can skip mongo logs). If your issue have anything related to other tools, please paste their config too.
```
 your-spotify-server:
    image: yooooomi/your_spotify_server
    container_name: your-spotify-server
    environment:
      API_ENDPOINT: ${SERVER_HOST}
      CLIENT_ENDPOINT: ${WEB_HOST}
      SPOTIFY_PUBLIC: ${SPOTIFY_PUBLIC}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}     
    restart: unless-stopped
```

```
  your-spotify-web:
    image: yooooomi/your_spotify_client
    container_name: your-spotify-web
    environment:
      API_ENDPOINT: ${SERVER_HOST}
    restart: unless-stopped
```
Logs contain a lot of personal data I would prefer not to share

**Screenshots**

![image](https://github.com/Yooooomi/your_spotify/assets/72750942/4ea4189f-0285-4c56-a5f3-1464805f05f3)
