### ISSUE TITLE
Timeouts on Spotify API

### ISSUE THREAD

**Issue by SuperKali** [Yooooomi/your_spotify#304]
**Describe the bug**

Very often it happens that I have to restart the applications because it doesn't let you log in anymore, I have some times the server that handles the API to Spotify stops communicating and you are forced to restart

```
version: "3"

services:
  your_spotify_server:
    container_name: your_spotify_server
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "127.0.0.1:8000:8080"
    links:
      - your_spotify_mongo
    depends_on:
      - your_spotify_mongo
    environment:
      API_ENDPOINT: https://api-spotify.example.com
      CLIENT_ENDPOINT: https://spotify.example.com
      SPOTIFY_PUBLIC: SECRET  # Add your Spotify public key here
      SPOTIFY_SECRET: SECRET  # Add your Spotify secret key here
      MONGO_ENDPOINT: mongodb://your_spotify_mongo:27017/your_spotify
  your_spotify_mongo:
    container_name: your_spotify_mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  your_spotify_web:
    container_name: your_spotify_web
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "127.0.0.1:8001:3000"
    environment:
      API_ENDPOINT: https://api-spotify.example.com
```
**Shared link**

https://paste.superkali.me/ositagejic.yaml
