### ISSUE TITLE
Duplicate Key Error in MongoDB During Import of streaming-history.json in Docker Container

### ISSUE THREAD

**Issue by xFrenchGamer73** [Yooooomi/your_spotify#312]
Hi,

I'm facing an issue with a MongoDB instance running in a Docker container. The problem arises when I attempt to import data from a `streaming-history.json` file into the `tracks` collection of my `your_spotify` database. I'm encountering a duplicate key error as follows:

![image](https://github.com/Yooooomi/your_spotify/assets/25753002/d11c38f9-0751-4e15-9637-9f177b83be75)

This error occurs specifically during the import process of the `streaming-history.json` file, causing data insertion failures due to a conflict with the `id` field, which is supposed to be unique. 

I am seeking advice on how to handle this issue, especially considering it seems to be related to MongoDB's handling of unique indexes within a containerized environment. Any tips on managing duplicate keys during JSON data import, or on configuring MongoDB in Docker to avoid such conflicts, would be highly appreciated.

Thank you for your assistance!

**Comment by xFrenchGamer73** [comment]
Compose file 
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://192.168.1.2:8080 # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: http://192.168.1.2:3000
      SPOTIFY_PUBLIC: 
      SPOTIFY_SECRET: 
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://192.168.1.2:8080
```
