### ISSUE TITLE
Not sure how to add multiple users

### ISSUE THREAD

**Issue by leddie24** [Yooooomi/your_spotify#320]
**Describe the bug**

I set up Your Spotify in a docker container in my Synology NAS. I successfully added myself to the dashboard and can start viewing data. When I log out, I tried to add my wife's account. It brings me to the auth page with username/password, and clicking submit just brings me to the Login screen without any warning or error.

**Expected behavior**

Expected to log in with a second user successfully, and not bring it back to the login

**Additional context**

Please paste the docker-compose file you're using to host YourSpotify and their logs (you can skip mongo logs). If your issue have anything related to other tools, please paste their config too.

```
  GNU nano 7.2                                                                                                docker-compose.yml                                                                                                           version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://192.168.68.72:8080 # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: http://192.168.68.72:3000
      SPOTIFY_PUBLIC: ___PUBLIC__
      SPOTIFY_SECRET: ___SECRET__
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://192.168.68.72:8080
```

**Screenshots**

**Shared link**

If you don't mind, you can add a Shared link to this issue by clicking **Share this page** on your YourSpotify application so that I can identify the issue quicker.
