### ISSUE TITLE
cant connect to mongodb

### ISSUE THREAD

**Issue by kajvans** [Yooooomi/your_spotify#325]
running the docker on a remote server and when i run the docker the server does not load anything
docker-compose.yml:
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: urlserver # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: urlclient
      SPOTIFY_PUBLIC: pub
      SPOTIFY_SECRET: priv
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: urlsever

networks:
  default:
    external: true
    name: services
```

i get this error on the server:
```
$ node ./lib/migrations.js
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
/app/node_modules/mongoose/lib/connection.js:805
    err = new ServerSelectionError();
          ^

MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
    at _handleConnectionErrors (/app/node_modules/mongoose/lib/connection.js:805:11)
    at NativeConnection.openUri (/app/node_modules/mongoose/lib/connection.js:780:11) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 176592678,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo ENOTFOUND mongo
            at connectionFailureError (/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/connect.js:379:20)
            at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/connect.js:285:22)
            at Object.onceWrapper (node:events:628:26)
            at Socket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:157:8)
            at emitErrorCloseNT (node:internal/streams/destroy:122:3)
            at processTicksAndRejections (node:internal/process/task_queues:83:21) {
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' },
          [cause]: Error: getaddrinfo ENOTFOUND mongo
              at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
            errno: -3007,
            code: 'ENOTFOUND',
            syscall: 'getaddrinfo',
            hostname: 'mongo'
          }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

also when running the command docker ps i dont see the mongodb docker
do i need to install mongodb myself or?
