### ISSUE TITLE
Server Crash: Error grabbing logs

### ISSUE THREAD

**Issue by NeoHBz** [Yooooomi/your_spotify#326]
**Describe the bug**

I rebooted my VM instance and restarted the docker apps. This resulted in:

```
error from daemon in stream: Error grabbing logs: invalid character 'l' after object key:value pair
```

<img width="1440" alt="Screenshot 2023-12-21 at 10 35 57 PM" src="https://github.com/Yooooomi/your_spotify/assets/56602090/59b431da-a8a0-4546-bf89-7f8ce6ed2cf8">

`docker-compose.yml`
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotifyserver.mywebsite.com
      - CLIENT_ENDPOINT=https://spotify.mywebsite.com
      - SPOTIFY_PUBLIC=PUBLIC
      - SPOTIFY_SECRET=SECRET
      - TIMEZONE=Asia/Kolkata
  mongo:
    container_name: mongo
    image: mongo:6.0
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=https://spotifyserver.mywebsite.com
```
