### ISSUE TITLE
Importing history from Spotify ignores blacklisted artists

### ISSUE THREAD

**Issue by MrSuttonmann** [Yooooomi/your_spotify#333]
**Describe the bug**

Importing history from Spotify ignores blacklisted artists.
I had blacklisted an artist, then imported my listening history. The artist then appears in stats.

**Expected behavior**

I do not expect a blacklisted artist to appear in the stats, regardless of when the data was imported.

**Additional context**

```
version: "3.3"
services:
  mongo6:
    container_name: mongo6
    image: mongo:6
    restart: unless-stopped
    networks:
      - mongo-network
  your-spotify:
    restart: unless-stopped
    image: lscr.io/linuxserver/your_spotify:latest
    ports:
      - 22000:80
      - 22443:443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - APP_URL=${APP_URL}
      - MONGO_ENDPOINT=${MONGO_ENDPOINT}
      - SPOTIFY_PUBLIC=${SPOTIFY_PUBLIC}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
    depends_on:
      - mongo6
    networks:
      - mongo-network
networks:
  mongo-network: {}
x-dockge:
  urls:
    - ${APP_URL}
```

**Screenshots**

![image](https://github.com/Yooooomi/your_spotify/assets/7480500/b6fc40dd-12e7-4ea7-a8ff-d53356d39e38)

![image](https://github.com/Yooooomi/your_spotify/assets/7480500/a461c3d1-9fc1-4674-a9ed-82bd175e59c2)

**Shared link**

https://soundstats.littleberrylodge.co.uk/?gname=All&token=8cbe326e-fb9d-4d0e-8768-d81c7698da16
