### ISSUE TITLE
Login button doesn't work when behind a reverse proxy

### ISSUE THREAD

**Issue by allw1994** [Yooooomi/your_spotify#335]
Bit of a weird one but open to suggestions. If I access the container directly using `http(s)://<docker-host>:3000` the login button redirects correctly to the `API_ENDPOINT` address. If I access through a reverse proxy using the full endpoint listed in `CLIENT_ENDPOINT` the page loads but shows `web application can't communicate with the server` and the login url is `http://localhost:8080/oauth/spotify`.

Tried settings the `CORS` environmental variable to all just to see if it was something along those lines but this hasn't done anything.

For reference the reverse proxy is external to the docker swarm but there are roughly 40 other services and servers sat behind the reverse proxy happily.

Here is the docker compose definition:
````
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://api.spotify-stats.domain.co.uk
      CLIENT_ENDPOINT: https://spotify-stats.domain.co.uk
      SPOTIFY_PUBLIC: aaaaaaaa
      SPOTIFY_SECRET: bbbbbbb
      TIMEZONE: Europe/London
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - /mnt/your-spotify:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - 3000:3000
    environment:
      API_ENDPOINT: https://api.spotify-stats.domain.co.uk
````
