### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by 0ghj04hjyg9045** [Yooooomi/your_spotify#34]
Whenever I try to run the Spotify server I get "API_ENDPOINT is not defined, web app won't work.", while API_ENDPOINT is set to http://localhost:8080

**Comment by Yooooomi** [comment]
Hello, sorry to hear this news. Can you share the `docker-compose` file(s) you're using to run the app? Thanks!

**Comment by 0ghj04hjyg9045** [comment]
```
version: "3"



services:

  app:

    container_name: express-mongo

    restart: always

    build: ./server

    ports:

      - "8080:8080"

    links:

      - mongo

    depends_on:

      - mongo

    environment:

      - API_ENDPOINT=http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard

      - CLIENT_ENDPOINT=http://localhost:3000

      - SPOTIFY_PUBLIC=<PLACEHOLDER>

      - SPOTIFY_SECRET=<PLACEHOLDER>

      - CORS=http://localhost:3000,http://localhost:3001

      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify

  mongo:

    container_name: mongo

    image: mongo



  web:

    container_name: web

    restart: always

    build: ./client

    ports:

      - "3000:3000"

    environment:

      - API_ENDPOINT=http://localhost:8080
```

**Comment by Yooooomi** [comment]
You should try to use the example `docker-compose` file, that is fetching the image from dockerhub instead of building it yourself.

**Comment by 0ghj04hjyg9045** [comment]
Thank you, I used the example instead and that seem to did something but got an error.

```
yarn run v1.22.5
$ node ./src/migrations.js
2021-05-06T21:11:53.128Z [debug]: Trying to connect to database
/app/node_modules/mongoose/lib/connection.js:845
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:845:32)
    at /app/node_modules/mongoose/lib/index.js:348:10
    at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1152:10)
    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:347:20)
    at connect (/app/src/database/index.js:12:33)
    at MongoDbStore.load (/app/src/migrations.js:8:11)
    at loadMigrationsIntoSet (/app/node_modules/migrate/lib/load-migrations.js:25:9)
    at Function.exports.load (/app/node_modules/migrate/index.js:53:3)
    at Object.<anonymous> (/app/src/migrations.js:31:9)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        error: Error: getaddrinfo ENOTFOUND mongo
            at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:69:26) {
          name: 'MongoNetworkError'
        },
        roundTripTime: -1,
        lastUpdateTime: 3107130,
        lastWriteDate: null,
        opTime: null,
        type: 'Unknown',
        topologyVersion: undefined,
        minWireVersion: 0,
        maxWireVersion: 0,
        hosts: [],
        passives: [],
        arbiters: [],
        tags: []
      }
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by Yooooomi** [comment]
Ok, it seems like the `mongo` address cannot be found. Can you send me the new `docker-compose` file you're using?

**Comment by 0ghj04hjyg9045** [comment]
Sure:
```

version: "3"



services:

  app:

    image: yooooomi/your_spotify_server

    container_name: express-mongo

    restart: always

    ports:

      - "8080:8080"

    links:

      - mongo

    depends_on:

      - mongo

    environment:

      - API_ENDPOINT=http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard

      - CLIENT_ENDPOINT=http://localhost:3000

      - SPOTIFY_PUBLIC=<PLACEHOLDER>

      - SPOTIFY_SECRET=<PLACEHOLDER>

      - CORS=http://localhost:3000,http://localhost:3001

      #- CORS=all

  mongo:

    container_name: mongo

    image: mongo

    volumes:

      - ./your_spotify_db:/data/db



  web:

    image: yooooomi/your_spotify_client

    container_name: web

    restart: always

    ports:

      - "3000:3000"

    environment:

      - API_ENDPOINT=http://localhost:8080
```
