### ISSUE TITLE
Graphs not getting loaded

### ISSUE THREAD

**Issue by GrumpyDevil** [Yooooomi/your_spotify#384]
Hey All,

The graphs are not getting loaded at all.

![image](https://github.com/Yooooomi/your_spotify/assets/21016172/e4e809cc-5cee-4347-9af0-7066cd11cab8)

**Comment by Yooooomi** [comment]
Hello, can you provide config files and logs (docker, browser)? thanks a lot

**Comment by GrumpyDevil** [comment]
Hey,

Please find the docker compose command below

version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: unless-stopped
    ports:
      - "3081:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.0.138:3080
      - CLIENT_ENDPOINT=http://192.168.0.138:3080
      - SPOTIFY_PUBLIC=${__your_spotify_client_id__}
      - SPOTIFY_SECRET=${__your_spotify_secret__}
      - i-want-a-security-vulnerability-and-want-to-allow-all-origins
      - TIMEZONE=Asia/India
  mongo:
    container_name: mongo-your-spotify
    image: mongo:4.4.8
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/your_spotify/DB:/data/db

  web:
    image: yooooomi/your_spotify_client
[_yourspotify-server-1_logs.txt](https://github.com/Yooooomi/your_spotify/files/14806463/_yourspotify-server-1_logs.txt)

    restart: unless-stopped
    ports:
      - "3080:3000"
    environment:
      - API_ENDPOINT=http://192.168.0.138:3081

**Comment by Yooooomi** [comment]
Hello, your API_ENDPOINT is wrong in the backend. It should be the one you set in the web service.

**Comment by GrumpyDevil** [comment]
Hey, 

I tried changing the API endPoint but its still not working.
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: unless-stopped
    ports:
      - "8888:8888"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.0.138:8888
      - CLIENT_ENDPOINT=http://192.168.0.138:3000
      - SPOTIFY_PUBLIC=${__your_spotify_client_id__}
      - SPOTIFY_SECRET=${__your_spotify_secret__}
      - i-want-a-security-vulnerability-and-want-to-allow-all-origins
      - TIMEZONE=${TZ}
  mongo:
    container_name: mongo-your-spotify
    image: mongo:4.4.8
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/your_spotify/DB:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://192.168.0.138:8888
```

![image](https://github.com/Yooooomi/your_spotify/assets/21016172/4148e3c9-62f7-41c7-874f-758b2ac1a160)
![image](https://github.com/Yooooomi/your_spotify/assets/21016172/ff1a2d00-e182-4a81-a4bb-6a6f545c639b)
