### ISSUE TITLE
Using a domain instead of local IP adresses: Can't get it to work

### ISSUE THREAD

**Issue by HexagonIsTheBestagon** [Yooooomi/your_spotify#389]
**Describe the bug**

After clicking on the login button, I get a completely blank page except of the usual dashboad. 

**Expected behavior**

Normal Login, I guess. 

**Additional context**

My compose file: 

```
services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8070:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://spotify.domain.cc # This MUST be included as a valid URL in the spotify dashboard
      CLIENT_ENDPOINT: https://spotify-server.domain.cc
      SPOTIFY_PUBLIC: here be dragons
      SPOTIFY_SECRET: here be dragons
      CORS: i-want-a-security-vulnerability-and-want-to-allow-all-origins

  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3002:3000"
    environment:
      API_ENDPOINT: https://spotify-server.domain.cc
```
![Screenshot 2024-04-11 185701](https://github.com/Yooooomi/your_spotify/assets/126624610/659e8255-1db8-4579-9d7b-a07cb6c6b966)

![Screenshot 2024-04-11 185722](https://github.com/Yooooomi/your_spotify/assets/126624610/2c045af8-f773-4201-949a-156f1753e2dc)

![Screenshot 2024-04-11 185502](https://github.com/Yooooomi/your_spotify/assets/126624610/427e9718-ae2e-404b-b198-e45b20874a6a)

**Comment by hkamran80** [comment]
In your `server` service, I think you have the `API_ENDPOINT` and `CLIENT_ENDPOINT` variables swapped.

**Comment by HexagonIsTheBestagon** [comment]
Ah, that was just for a test. Doesn't work either way, sadly. 
Here's my cloudflare tunnel: 

![Screenshot 2024-04-11 191550](https://github.com/Yooooomi/your_spotify/assets/126624610/01dcaee9-e448-4131-b766-46050110bae7)

Excuse the bad readability.

**Comment by hkamran80** [comment]
I found that I could only use it via my Cloudflare Tunnel setup. Accessing it on any other hostname (even with the appropriate CORS and other settings) failed.

**Comment by HexagonIsTheBestagon** [comment]
I'm not a native English speaker, may you explain it to me again? I am accessing it through a cloudflare tunnel. Is that not possible?

**Comment by hkamran80** [comment]
When you go to YS, do you use your Cloudflare Tunnel setup or do you use the IP address?

**Comment by HexagonIsTheBestagon** [comment]
I use my cloudflare tunnel: spotify.[domain].cc

**Comment by HexagonIsTheBestagon** [comment]
That said, it did work correctly when just accessing it over my local ip.

**Comment by hkamran80** [comment]
Huh. I have nothing then.

**Comment by HexagonIsTheBestagon** [comment]
I will wait for Yoomi then, thanks.

**Comment by Vahelnir** [comment]
Hey, it looks like your `API_ENDPOINT` might be wrong.

You have `API_ENDPOINT: https://spotify.domain.cc` in the `server` service, and `API_ENDPOINT: https://spotify-server.domain.cc ` in the `client`service.
If your API is on `spotify-server.[domain].cc` and your client is on `spotify.[domain].cc`, then your `API_ENDPOINT` should be `spotify-server.[domain].cc` and `CLIENT_ENDPOINT` should be `spotify.[domain].cc`.

Also, make sure the spotify public & secret tokens you wrote in the issue are invalidated. 


If you want an example, I have my API on `https://music.[mydomain].fr/api` and the client on `https://music.[mydomain].fr`.
<details>
  <summary>My compose.yml</summary>
  
  ```yml
  version: "3"
  services:
    server:
      image: yooooomi/your_spotify_server
      restart: always
      ports:
        - "8081:8080"
      links:
        - mongo
      depends_on:
        - mongo
      environment:
        API_ENDPOINT: https://music.[mydomain].fr/api
        CLIENT_ENDPOINT: https://music.[mydomain].fr
        SPOTIFY_PUBLIC: ${SPOTIFY_PUBLIC_KEY}
        SPOTIFY_SECRET: ${SPOTIFY_SECRET_KEY}
        CORS: https://music.[mydomain].fr
  
    mongo:
      image: mongo:6
      volumes:
        - ./your_spotify_db:/data/db
  
    web:
      image: yooooomi/your_spotify_client
      restart: always
      ports:
        - "8082:3000"
      environment:
        API_ENDPOINT: https://music.[mydomain].fr/api
  ```
</details>


Hope I'm not wrong and that fixes your issue!
