### ISSUE TITLE
API Call and INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by hardball2-0** [Yooooomi/your_spotify#394]
### Discussed in https://github.com/Yooooomi/your_spotify/discussions/393

<div type='discussions-op-text'>

<sup>Originally posted by **hardball2-0** April 26, 2024</sup>
Hey ! 

I'm actually trying to deploy the "app" but when i make the connectivity with the api I still have INVALID_CLIENT: Invalid redirect URI

Some body have any idea ? 

**Environnement** 

Docker 
Nginx proxy manager 

Actually my conf is like that :

**Spotify dev redirect URI** :

http://public_ip_of_my_server:port/callback
https://my_web_interface/callback
http://public_ip_of_my_server:port/oauth/spotify

In the web interface i still having the message "The web application can't communicate with the server"

**Docker conf**

```
 version: "3"
 
 services:
   server:
     image: yooooomi/your_spotify_server
     container_name: api
     networks:
      - reverse
     restart: always
     ports:
       - "437:8080"
     links:
       - mongo
     depends_on:
       - mongo
     environment:
       - API_ENDPOINT=http://public_ip_of_my_server:437 #it's reacheable 
       - CLIENT_ENDPOINT=https://my_web_interface  #it's reacheable too
       - SPOTIFY_PUBLIC=my_public_id
       - SPOTIFY_SECRET=my_secret

   mongo:
     image: mongo:6 #the connexion is working between all apps
     networks:
      - reverse
     volumes:
       - /opt/spot/your_spotify_db:/data/db
 
   web:
     image: yooooomi/your_spotify_client
     container_name: web
     networks:
      - reverse
     restart: always
     ports:
       - "3000:3000"
     environment:
       - API_ENDPOINT=http://public_ip_of_my_server:437
 networks:
   reverse:
    external: true
    name: reverse
```

Any idea?</div>
