### ISSUE TITLE
Web application can't communicate with server - NGINX Proxy manager reverse proxy + docker

### ISSUE THREAD

**Issue by kmanwar89** [Yooooomi/your_spotify#400]
Hi,

I've gone through just about every single issue I can find trying to find a solution, and I've tried every combination I can think of, but I'm having the worst time trying to access this application through my reverse proxy (NGINX proxy manager).

I previously had it working on a much older version, but shut down my server and was away from self hosting focusing on school for several months.  I'm getting back into the swing of things, and this is one of the last apps I have left to work through.

I'm receiving, much like other folks have reported, the "Web application can't communicate with server" error when trying to access at my FQDN through my reverse proxy.  I have been able to successfully set it up using just localhost networking, but ultimately that isn't how my final setup is configured.

I am using a custom domain, with Cloudflare tunnels. I have two Docker networks, one between the CF tunnel and NPM, and the other between NPM and the downstream services. The flow looks something like:

Request --> cloudflare --> cf tunnel --> NPM --> downstream service 
<---------------------------------------------------------------------------response

Here's my compose file:

```
---
services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
#      - "8080:8080"
      - "8000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://music.api.**DOMAIN**.com # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: http://music.**DOMAIN**.com/oauth/spotify
      SPOTIFY_PUBLIC: <VALUE>
      SPOTIFY_SECRET: <VALUE>
      CORS: i-want-a-security-vulnerability-and-want-to-allow-all-origins #Yes I know this is a bad idea - this is JUST for testing
      MONGO_ENDPOINT: mongodb://mongo:27017/your_spotify
      TIMEZONE: America/New_York
    networks:
      - npm_cf

  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db
    networks:
      - npm_cf

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
#      - "3000"
    environment:
      API_ENDPOINT: http://api.music.**DOMAIN**.com
    networks:
      - npm_cf

networks:  # Docker network that only communicates between reverse proxy + cloudflare daemon
  npm_cf:
    name: npm_cf
    external: true
```
Here's my spotify dashboard setup (at the time of opening this issue):
![spotify setup](https://github.com/Yooooomi/your_spotify/assets/11323060/c1be9df1-8ebf-4561-847d-ce90d2f87d40)

And here's all the different iterations I've tried...I can't quite seem to wrap my head around which is actually needed, or why this error is occurring:

```
http://music.DOMAIN.com/oauth/spotify/callback
https://music.DOMAIN.com/oauth/spotify/callback

http://api.music.DOMAIN.com/oauth/spotify/callback
https://api.music.DOMAIN.com/oauth/spotify/callback

http://music.DOMAIN.com/api/oauth/spotify/callback
https://music.DOMAIN.com/api/oauth/spotify/callback

http://api.music.DOMAIN.com/api/oauth/spotify/callback
https://api.music.DOMAIN.com/oapi/auth/spotify/callback
```

I've consulted the following issues to try to find a solution, but haven't come across one that works, which is why I'm opening a new issue. I appreciate any help you can provide, and thank you for creating this software!!

https://github.com/Yooooomi/your_spotify/issues/55
https://github.com/Yooooomi/your_spotify/issues/74
https://github.com/Yooooomi/your_spotify/issues/296
https://github.com/Yooooomi/your_spotify/issues/344
https://github.com/Yooooomi/your_spotify/issues/371
https://github.com/Yooooomi/your_spotify/issues/226
https://github.com/Yooooomi/your_spotify/issues/208

**Comment by renolation** [comment]
here is my portainer stack docker compose, hope it helps
i help npm also in this server, just map port to domain like below.
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8085:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://spotify-server.xxx.com # This MUST be included as a valid URL in the spotify dashboard
      CLIENT_ENDPOINT: https://spotify.xxx.com
      SPOTIFY_PUBLIC: xxx
      SPOTIFY_SECRET: xxx
      CORS: i-want-a-security-vulnerability-and-want-to-allow-all-origins

  mongo:
    container_name: mongo
    restart: always
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3005:3000"
    environment:
      API_ENDPOINT: https://spotify-server.xxx.com
```

**Comment by kmanwar89** [comment]
> here is my portainer stack docker compose, hope it helps i help npm also in this server, just map port to domain like below.
> 
> ```
> version: "3"
> 
> services:
>   server:
>     image: yooooomi/your_spotify_server
>     restart: always
>     ports:
>       - "8085:8080"
>     links:
>       - mongo
>     depends_on:
>       - mongo
>     environment:
>       API_ENDPOINT: https://spotify-server.xxx.com # This MUST be included as a valid URL in the spotify dashboard
>       CLIENT_ENDPOINT: https://spotify.xxx.com
>       SPOTIFY_PUBLIC: xxx
>       SPOTIFY_SECRET: xxx
>       CORS: i-want-a-security-vulnerability-and-want-to-allow-all-origins
> 
>   mongo:
>     container_name: mongo
>     restart: always
>     image: mongo:6
>     volumes:
>       - ./your_spotify_db:/data/db
> 
>   web:
>     image: yooooomi/your_spotify_client
>     restart: always
>     ports:
>       - "3005:3000"
>     environment:
>       API_ENDPOINT: https://spotify-server.xxx.com
> ```

Looks almost identical to my setup - I'm suspecting there is something at play here with NPM, as bringing up the container without NPM and just pointing to localhost works without issue.

FYI you don't need the "version" command at the top of the compose file anymore - that's been deprecated

**Comment by RagingCactus** [comment]
Please take a look at the following lines from your configuration:
```yaml
services:
  server:
# [...]
    environment:
      API_ENDPOINT: http://music.api.**DOMAIN**.com # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: http://music.**DOMAIN**.com/oauth/spotify
# [...]

  web:
# [...]
    environment:
      API_ENDPOINT: http://api.music.**DOMAIN**.com
# [...]
```

Your `API_ENDPOINT` definitions do not match. Is your posted configuration accurate to what you're using?

Also, please post any errors you can see in the browser development console, browser network tab and server log.

**Comment by FNTK-Francis** [comment]
I am trying to use the same setup ... Caddy Reverse proxy in front of dockerstack on Portainer ... works up to the login page/button but then just gives me a blank screen on the /oauth/spotify endpoint.

Caddy Setup: 
 - https://myspotify.domain.tld
         - reverse_proxy /oauth/spotify/callback  backend:15000
         - reverse_proxy /* backend:3000

Compose File:
services:
  server:
    image: yooooomi/your_spotify_server:latest
    restart: always
    ports:
      - "15000:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://myspotify.domain.tld
      CLIENT_ENDPOINT: https://myspotify.domain.tld
      SPOTIFY_PUBLIC: ....
      SPOTIFY_SECRET: ....
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: https://myspotify.domain.tld


Any idea what I am doing wrong ?

**Comment by FNTK-Francis** [comment]
Update ... It seems that there is some sort of dependency in the webcode on the ports ? If I reverseproxy the ports directly, it works without any issues.
So to summarize:
Reverse proxying through https ==> backend:3000 = Client Webinterface OK but cannot login
Reverse proxying through https:3000 ==> backend:3000 = All OK ...

I did some more tests to corroborate my findings, but I guess the application requires a URI with a :port in it. ?

**Comment by luiscachog** [comment]
Same issue here...

**Comment by david-askari** [comment]
The following works for me using Caddy and being within my home network, since the DNS A record of the wildcard domain `*.domain.tld` points to the internal IP address.

The redirect URL within Spotify developer is `https://spotify-api.domain.tld/oauth/spotify/callback`.

Caddyfile:
```Caddyfile
*.domain.tld {
	@spotify host spotify.domain.tld
	handle @spotify {
		reverse_proxy localhost:3000
	}
	
	@spotify-api host spotify-api.domain.tld
	handle @spotify-api {
		reverse_proxy localhost:8080
	}
```

Docker Compose file:
```yaml
name: your-spotify

services:
  server:
    container_name: your_spotify_server
    image: yooooomi/your_spotify_server:${VERSION}
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://spotify-api.domain.tld # This MUST be included as a valid URL in the spotify dashboard
      CLIENT_ENDPOINT: https://spotify.domain.tld
      SPOTIFY_PUBLIC: ${SPOTIFY_PUBLIC}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}

  mongo:
    container_name: mongo
    image: mongo:4.4 # old mongo version due to https://github.com/docker-library/mongo/issues/485#issuecomment-891991814 but shouldn't matter in this context
    restart: always
    volumes:
      - ./your_spotify_db:/data/db

  web:
    container_name: your_spotify_client
    image: yooooomi/your_spotify_client:${VERSION}
    restart: always
    ports:
      - 3000:3000
    environment:
      API_ENDPOINT: https://spotify-api.domain.tld
```
