### ISSUE TITLE
Doesn't work with `http_proxy` enviroment variable

### ISSUE THREAD

**Issue by kzvdar42** [Yooooomi/your_spotify#401]
**Describe the bug**

I need to run this app behind http proxy for it to properly work. But app fails to run behind proxy, as all requests to github or spotify fail with `ERR_FR_TOO_MANY_REDIRECTS` (as seen in logs)

**Expected behavior**

App should work with provided http proxy

**Additional context**

my `docker-compose.yaml`:
```
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8383:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://spot.local/api # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: http://spot.local
      SPOTIFY_PUBLIC: *public*
      SPOTIFY_SECRET: *secret*
      HTTPS_PROXY: http://192.168.0.5:50053
      https_proxy: http://192.168.0.5:50053
      HTTP_PROXY: http://192.168.0.5:50053
      http_proxy: http://192.168.0.5:50053
      no_proxy: localhost,172.16.0.0/16,spot.local
      NO_PROXY: localhost,172.16.0.0/16,spot.local
      COOKIE_VALIDITY_MS: 1000h
  mongo:
    container_name: mongo
    image: mongo:6
    restart: always
    volumes:
      - /shared/db:/data/db
  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3300:3000"
    environment:
      API_ENDPOINT: http://spot.local/api
```
