### ISSUE TITLE
Login Problems

### ISSUE THREAD

**Issue by Its4Nik** [Yooooomi/your_spotify#403]
So I saw this project and wanted to try it out, but I can't seem to get further than running it, actually using it doesn't work.

```yaml
  server:
    image: yooooomi/your_spotify_server
    restart: always
    container_name: spotify-server
    ports:
      - "8180:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://stats.XXX.de
      CLIENT_ENDPOINT: https://api-stats.XXX.de/
      SPOTIFY_PUBLIC: XXXXXX
      SPOTIFY_SECRET: XXXXXX
      CORS: i-want-a-security-vulnerability-and-want-to-allow-all-origins

  mongo:
    container_name: spotify-db
    image: mongo:6
    volumes:
      - ./spotify_db:/data/db

  web:
    container_name: spotify-client
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3004:3000"
    environment:
      API_ENDPOINT: https://stats.XXX.de
```

And those are my redirect URIs:

```
    https://api-stats.XXX.de/oauth/spotify/callback
    https://api-stats.XXX.de/oauth/spotify
    https://stats.XXX.de/oauth/spotify/callback
    https://stats.XXX.de/oauth/spotify
    https://stats.XXX.de
```

![image](https://github.com/Yooooomi/your_spotify/assets/106100177/26bf00af-d89f-45a9-ad6e-6fb027e94f71)

This is the login page:
![image](https://github.com/Yooooomi/your_spotify/assets/106100177/cd82b1ed-3521-43c2-b192-85e72477b0ed)

**Comment by RagingCactus** [comment]
```yaml
      API_ENDPOINT: https://stats.XXX.de
      CLIENT_ENDPOINT: https://api-stats.XXX.de/
```

That seems to be the wrong way around doesn't it?

Also, I'd recommend removing the `CORS` variable entirely, your deployment will work without setting it to any value manually.

**Comment by Its4Nik** [comment]
> ```yaml
>       API_ENDPOINT: https://stats.XXX.de
>       CLIENT_ENDPOINT: https://api-stats.XXX.de/
> ```
> 
> That seems to be the wrong way around doesn't it?
> 
> Also, I'd recommend removing the `CORS` variable entirely, your deployment will work without setting it to any value manually.

yeah, i changed it thanks, but it still doesn't show up (also after removing cors). Console log is clear.


And the container logs (server, client, db) are all clear (no errors only stdout) as well

**Comment by RagingCactus** [comment]
Did you change the values in both the `server` and `web` containers? Are you sure both containers were recreated properly after changing the setting?

Also, if the problem persists after checking both of the above: Please describe in detail what happens when you press the login button. To which URL are you redirected to? Is the browser console clear of errors? Does the network tab show any errors?

**Comment by Its4Nik** [comment]
> Again, please submit all the information you have. What happens in what order when you press which button? Is that the full URL you are being redirected to? (It pretty much can't be; the backend displays "Hello !" on its `/` index page, so the page wouldn't be empty) Also, please supply relevant logs from the frontend, backend, and browser.


On the login Site:
Docker compose:
```yaml
 server:
    image: yooooomi/your_spotify_server
    restart: always
    container_name: spotify-server
    ports:
      - "8180:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://api-stats.XXX.de/
      CLIENT_ENDPOINT: https://stats.XXX.de/
      SPOTIFY_PUBLIC: XXX
      SPOTIFY_SECRET: XXX
      CORS: i-want-a-security-vulnerability-and-want-to-allow-all-origins

  mongo:
    container_name: spotify-db
    image: mongo:6
    volumes:
      - ./spotify_db:/data/db

  web:
    container_name: spotify-client
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3004:3000"
    environment:
      API_ENDPOINT: https://api-stats.XXX.de/
```

Console error:
´´´
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api-stats.XXX.de/me. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 301.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api-stats.XXX.de/me. (Reason: CORS request did not succeed). Status code: (null).

Object { stack: "ec@https://stats.XXX.de/static/js/main.e3d08b6e.js:2:402371\nHc</</u.onerror@https://stats.XXX.de/static/js/main.e3d08b6e.js:2:417263\n", message: "Network Error", name: "AxiosError", code: "ERR_NETWORK", config: {…}, request: XMLHttpRequest }
[thunk.ts:24:14](https://stats.XXX.de/static/js/services/redux/modules/user/thunk.ts)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api-stats.XXX.de/global/preferences. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 301.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api-stats.XXX.de/global/preferences. (Reason: CORS request did not succeed). Status code: (null).

Object { stack: "ec@https://stats.XXX.de/static/js/main.e3d08b6e.js:2:402371\nHc</</u.onerror@https://stats.XXX.de/static/js/main.e3d08b6e.js:2:417263\n", message: "Network Error", name: "AxiosError", code: "ERR_NETWORK", config: {…}, request: XMLHttpRequest }
´´´

When I press login it redirects to:

https://api-stats.XXX.de/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004/32:3004//oauth/spotify

So I guess something is wrong with my redirect?

When I adjust the redirect manually it goes back to the same page.

**Comment by Its4Nik** [comment]
Wait a second...

I accidentally added my subnet in nginx 132.XXX.XXX.XXX/32 like this.......

I'm going to try again I'm terribly sorry if this was the error

**Comment by Its4Nik** [comment]
Still get these errors:

```javascript
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api-stats.XXX.de/me. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Object { stack: "ec@https://stats.XXX.de/static/js/main.e3d08b6e.js:2:402371\nHc</</u.onerror@https://stats.XXX.de/static/js/main.e3d08b6e.js:2:417263\n", message: "Network Error", name: "AxiosError", code: "ERR_NETWORK", config: {…}, request: XMLHttpRequest }
[thunk.ts:24:14](https://stats.XXX.de/static/js/services/redux/modules/user/thunk.ts)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api-stats.XXX.de/global/preferences. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Object { stack: "ec@https://stats.XXX.de/static/js/main.e3d08b6e.js:2:402371\nHc</</u.onerror@https://stats.XXX.de/static/js/main.e3d08b6e.js:2:417263\n", message: "Network Error", name: "AxiosError", code: "ERR_NETWORK", config: {…}, request: XMLHttpRequest }
[thunk.ts:28:14](https://statsXXX.de/static/js/services/redux/modules/settings/thunk.ts)​
```

and when I click on login it redirects to:
https://api-stats.XXX.de//oauth/spotify

and then to:
https://oauth/spotify


---

```yaml
  server:
    image: yooooomi/your_spotify_server
    restart: always
    container_name: spotify-server
    ports:
      - "8180:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://api-stats.XXX.de
      CLIENT_ENDPOINT: https://stats.XXX.de
      SPOTIFY_PUBLIC: XXX
      SPOTIFY_SECRET: XXX
      CORS: i-want-a-security-vulnerability-and-want-to-allow-all-origins

  mongo:    container_name: spotify-db
    image: mongo:6
    volumes:
      - ./spotify_db:/data/db

  web:
    container_name: spotify-client
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3004:3000"
    environment:
      API_ENDPOINT: https://api-stats.XXX.de
```
