### ISSUE TITLE
Login button redirects to localhost despite API_ENDPOINT being configured to domain

### ISSUE THREAD

**Issue by ciarafair** [Yooooomi/your_spotify#415]
No matter what I do, the login button will redirect to a localhost address instead of the domain that is configured. I'm also getting an error saying that the web application cannot communicate with the server.

<img width="1528" alt="Screenshot 2024-08-01 at 11 57 25 AM" src="https://github.com/user-attachments/assets/597dd111-0e2f-4375-acb7-2e34e5898100">

<img width="381" alt="Screenshot 2024-08-01 at 11 56 07 AM" src="https://github.com/user-attachments/assets/c8c30a5f-4f84-4709-ba13-d86bfa633f7c">

I'm using a cloudflare tunnel to access the localhosted applications, there aren't any overlapping ports, ive triple checked.

![Cloudflare Setup](https://github.com/user-attachments/assets/7911834d-c885-48b6-a940-2c49bc19ebdd)

This is my docker compose file:

```
services:
  server:
    container_name: server
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://yourserver.[domain]/
      - CLIENT_ENDPOINT=https://yourspotify.[domain]
      - SPOTIFY_PUBLIC=[public key]
      - SPOTIFY_SECRET=/run/secrets/spotify_secret
      # MONGO_ENDPOINT: mongodb://192.168.50.3:27017/your_spotify
      - CORS=https://yourspotify.[domain],https://yourserver.[domain]
    networks:
      YourSpotify:
        ipv4_address: 192.168.50.4

  mongo:
    restart: always
    container_name: mongo
    image: mongo:6
    volumes:
      - /your_spotify_db:/data/db
    ports:
     - 27017:27017
    networks:
      YourSpotify:
        ipv4_address: 192.168.50.3

  web:
    container_name: client
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=https://yourserver.[domain]/
    networks:
      YourSpotify:
        ipv4_address: 192.168.50.2

networks:
  YourSpotify:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/24
          gateway: 192.168.50.1

secrets:
  spotify_secret:
    file: /secrets/SPOTIFY_SECRET
```

I can get to the spotify login-screen by manually going to my API and changing the address from https://yourserver.[domain] to https://yourserver.[domain]/oauth/spotify/callback but it immediately redirects me back to the localhost screen once the server API sends me back to the client.

This is genuinely driving me insane. How can I fix this?

Quick edit: These are the logs for the client and server

Client:
![Untitled design](https://github.com/user-attachments/assets/7ecfa6e2-8552-4fe3-afb4-bae6805667ac)

Server:
<img width="1076" alt="Screenshot 2024-08-01 at 12 16 26 PM" src="https://github.com/user-attachments/assets/aa8ca595-4577-4257-8852-85f4471f3cfc">
