### ISSUE TITLE
req.cookies is undefined on router.get("/spotify/callback", ...)

### ISSUE THREAD

**Issue by NeoHBz** [Yooooomi/your_spotify#419]
## Describe the bug

I hosted "YourSpotify" on a server, made a local tunnel to login - which works.
But when I try to login on domain, I get the below error(s):
```
GET /me 304 0.678 ms - -
GET /global/preferences 304 5.517 ms - -
[info]  [DbLoop] starting for 1 users
[info]  [@REDACTED_MY_NAME]: refreshing...
[info]  No missing tracks, passing...
[info]  [@REDACTED_MY_NAME]: 0 tracks, 0 albums, 0 artists
GET /me 304 0.544 ms - -
GET /global/preferences 304 4.044 ms - -
GET /oauth/spotify 302 1.599 ms - 808
[error]  ZodError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [],
    "message": "Required"
  }
]
    at Object.get error [as error] (/app/node_modules/zod/lib/types.js:43:31)
    at ZodObject.parse (/app/node_modules/zod/lib/types.js:143:22)
    at /app/apps/server/src/routes/oauth.ts:88:49
    at Generator.next (<anonymous>)
    at /app/apps/server/src/routes/oauth.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/apps/server/src/routes/oauth.ts:4:12)
    at /app/apps/server/src/routes/oauth.ts:83:22
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:149:13) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'undefined',
      path: [],
      message: 'Required'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'undefined',
      path: [],
      message: 'Required'
    }
  ]
}
GET /oauth/spotify/callback?code=REDACTED_CODE&state=REDACTED_STATE 302 5.345 ms - 92
GET /me 304 0.881 ms - -
GET /global/preferences 304 2.888 ms - -
[info]  [DbLoop] starting for 1 users
[info]  [@REDACTED_MY_NAME]: refreshing...
```

## Expected behavior

Login should work as it does when localtunneling

### Browser Console:
```
Refused to load the script 'https://static.cloudflareinsights.com/beacon.min.js/REDACTED' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

bundle.js:sourcemap:148783 Refused to connect to 'wss://music.domain.com:3000/ws' because it violates the following Content Security Policy directive: "connect-src 'self' http://localhost:8080/".
bundle.js:sourcemap:118056 
```
Which I tried bypassing by editing the `<meta>` in `index.js`:
```
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; object-src 'none'; script-src 'self' https://static.cloudflareinsights.com 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' https://i.scdn.co; connect-src 'self' https://musicapi.domain.com/;" />
```
### Compose file
docker-compose-dev.yml
```
services:
  app:
    container_name: your_spotify_server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        NODE_ENV: development
    volumes:
      - ./apps/server/src/:/app/apps/server/src/
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      # LOG_LEVEL: debug
      API_ENDPOINT: https://musicapi.domain.com
      CLIENT_ENDPOINT: https://music.domain.com
      SPOTIFY_PUBLIC: REDACTED_KEY
      SPOTIFY_SECRET: REDACTED_SECRET
      CORS: i-want-a-security-vulnerability-and-want-to-allow-all-origins
      TIMEZONE: Asia/Kolkata

  mongo:
    container_name: mongo
    image: mongo:6
    logging:
      driver: none
    volumes:
      - ./your_spotify_db:/data/db
    ports:
      - "27017:27017"

  web:
    container_name: your_spotify_web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        NODE_ENV: development
    volumes:
      - ./apps/client/src:/app/apps/client/src/
      - ./apps/client/public:/app/apps/client/public/
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      API_ENDPOINT: http://localhost:8080
```

## Screenshots

N/A - can't open dashboard on public domain

## Shared link

N/A - can't open dashboard on public domain
