### ISSUE TITLE
Graphs showing stale data

### ISSUE THREAD

**Issue by NevetsCJ** [Yooooomi/your_spotify#442]
**Describe the bug**

I found this project a couple of days ago, and I absolutely love it. I've came across an issue today where the graphs showing in the UI are outdated. 

At 12pm today I noticed that graphs had stopped updating themselves at 11pm last night. However, at 2pm today some graphs are correct, while others are still outdated. **Listening distribution over day** and **Best artists for hour of day** are both stuck at 11pm last night. **Average album release date** is also at 1pm today rather than 2pm.

Apologies if I haven't explained this very well. If there's further info or clarification needed just let me know :)

**Expected behavior**

Graphs shown in the UI should be up to date.

**Additional context**

I have Your-Spotify running in Docker, this is my config:
```yaml
services:
  server:
    image: yooooomi/your_spotify_server
    container_name: your-spotify-server
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://your-spotify-server.gcw.net
      CLIENT_ENDPOINT: https://your-spotify.gcw.net
      # CORS: your-spotify.gcw.net,your-spotify-server.gcw.net
      SPOTIFY_PUBLIC: REMOVED
      SPOTIFY_SECRET: REMOVED
    restart: always
    networks:
      - big-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.your-spotify-server.entrypoints=websecure"
      - "traefik.http.routers.your-spotify-server.tls=true"
      - "traefik.http.routers.your-spotify-server.rule=Host(`your-spotify-server.gcw.net`)"
      - "traefik.http.services.your-spotify-server.loadbalancer.server.port=8080"
      - "traefik.docker.network=your-spotify-server_ingress"
  
  mongo:
    container_name: your-spotify-database
    image: mongo:4.4.0
    volumes:
      - ./your-spotify/db:/data/db
    networks:
      - big-network

  web:
    image: yooooomi/your_spotify_client
    container_name: your-spotify-client
    links:
      - server
    depends_on:
      - server
    environment:
      API_ENDPOINT: https://your-spotify-server.gcw.net
    restart: always
    networks:
      - big-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.your-spotify.entrypoints=websecure"
      - "traefik.http.routers.your-spotify.tls=true"
      - "traefik.http.routers.your-spotify.rule=Host(`your-spotify.gcw.net`)"
      - "traefik.http.services.your-spotify.loadbalancer.server.port=3000"
      - "traefik.docker.network=your-spotify_ingress"
    
networks:
    big-network:
        external: true
```

In the console I can see it requesting up to date information
```
your-spotify-client    |  HTTP  10/28/2024 2:35:23 PM 172.19.0.2 GET /all
your-spotify-client    |  HTTP  10/28/2024 2:35:23 PM 172.19.0.2 Returned 200 in 3 ms
your-spotify-client    |  HTTP  10/28/2024 2:35:23 PM 172.19.0.2 GET /variables.js
your-spotify-client    |  HTTP  10/28/2024 2:35:23 PM 172.19.0.2 Returned 200 in 8 ms
your-spotify-client    |  HTTP  10/28/2024 2:35:23 PM 172.19.0.2 GET /static/js/main.4ee1a6ce.js
your-spotify-client    |  HTTP  10/28/2024 2:35:23 PM 172.19.0.2 Returned 200 in 4 ms
your-spotify-client    |  HTTP  10/28/2024 2:35:23 PM 172.19.0.2 GET /static/css/main.fa34713a.css
your-spotify-client    |  HTTP  10/28/2024 2:35:23 PM 172.19.0.2 Returned 200 in 3 ms
your-spotify-client    |  HTTP  10/28/2024 2:35:23 PM 172.19.0.2 GET /favicon.ico
your-spotify-client    |  HTTP  10/28/2024 2:35:23 PM 172.19.0.2 Returned 200 in 5 ms
your-spotify-server    | GET /me 200 16.050 ms - 475
your-spotify-server    | GET /accounts 200 35.719 ms - 113
your-spotify-server    | GET /global/preferences 200 12.130 ms - 68
your-spotify-server    | GET /spotify/top/artists?start=2024-10-27T14:35:21.870Z&end=2024-10-28T14:35:21.870Z&nb=20&offset=0 200 125.250 ms - 28370
your-spotify-server    | GET /spotify/top/hour-repartition/artists?start=2024-10-27T14:35:21.870Z&end=2024-10-28T14:35:21.870Z 200 131.977 ms - 95866
your-spotify-server    | GET /spotify/most_listened_artist?start=2024-10-27T14:35:21.870Z&end=2024-10-28T14:35:21.870Z&timeSplit=hour 200 202.706 ms - 63087
your-spotify-server    | GET /spotify/time_per?start=2024-10-27T14:35:21.870Z&end=2024-10-28T14:35:21.870Z&timeSplit=hour 200 163.415 ms - 680
your-spotify-server    | GET /spotify/songs_per?start=2024-10-27T14:35:21.870Z&end=2024-10-28T14:35:21.870Z&timeSplit=hour 200 141.822 ms - 785
your-spotify-server    | GET /spotify/different_artists_per?start=2024-10-27T14:35:21.870Z&end=2024-10-28T14:35:21.870Z&timeSplit=hour 200 250.997 ms - 87926
your-spotify-server    | GET /spotify/time_per_hour_of_day?start=2024-10-27T14:35:21.870Z&end=2024-10-28T14:35:21.870Z 200 95.449 ms - 218
your-spotify-server    | GET /spotify/feat_ratio?start=2024-10-27T14:35:21.870Z&end=2024-10-28T14:35:21.870Z&timeSplit=hour 200 126.143 ms - 1331
your-spotify-server    | GET /spotify/album_date_ratio?start=2024-10-27T14:35:21.870Z&end=2024-10-28T14:35:21.870Z&timeSplit=hour 200 167.689 ms - 900
your-spotify-server    | GET /version 200 453.995 ms - 35
your-spotify-server    | GET /spotify/popularity_per?start=2024-10-27T14:35:21.870Z&end=2024-10-28T14:35:21.870Z&timeSplit=hour 200 139.426 ms - 949
```

**Screenshots**

![2pm All Stats](https://github.com/user-attachments/assets/210ad0e9-4f3f-45ed-b2ed-79827670bade)

**Shared link**

Unable to access my instance externally.
