### ISSUE TITLE
Unable to run on IDX

### ISSUE THREAD

**Issue by luc1d-ed** [Yooooomi/your_spotify#448]
I wanted to run the project on the cloud and avoid installing docker on my PC. I have followed the README and configured everything correctly on the example config file. However I can't get it to run, the database does not recognize the user (Screenshot below).  It says:

` server-1  | [info]  [DbLoop] starting for 0 users`

Also the website displays that it is unable to contact to the server, which for context also did when I ran locally and I safely ignored because it still used to work, but that is not the case here.

**Expected behavior**

The website should be able to communicate with the server and display properly.

**Additional context**

DOCKER-CONFIG

```
services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard
      CLIENT_ENDPOINT: http://localhost:3000
      SPOTIFY_PUBLIC: [redacted]
      SPOTIFY_SECRET: [redacted]
      CORS: http://localhost:3000,http://localhost:3001 # "i-want-a-security-vulnerability-and-want-to-allow-all-origins" if you want to allow every origin

  mongo:
    container_name: mongo
    image: mongo:6
    restart: always
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://localhost:8080

```

DEV.NIX  (Used to configure IDX workspace)

```
# To learn more about how to use Nix to configure your environment
# see: https://developers.google.com/idx/guides/customize-idx-env
{ pkgs, ... }: {
  # Which nixpkgs channel to use.
  channel = "stable-24.05"; # or "unstable"

  # Use https://search.nixos.org/packages to find packages
  packages = [
    # pkgs.go
     pkgs.python311
     pkgs.python311Packages.pip
     pkgs.docker-compose
    # pkgs.nodejs_20
    # pkgs.nodePackages.nodemon
  ];

  # Sets environment variables in the workspace
  env = {};
  services.docker.enable = true;
  idx = {
    # Search for the extensions you want on https://open-vsx.org/ and use "publisher.id"
    extensions = [
      # "vscodevim.vim"
    ];

    # Enable previews
    previews = {
      enable = true;
      previews = {
        # web = {
        #   # Example: run "npm run dev" with PORT set to IDX's defined port for previews,
        #   # and show it in IDX's web preview panel
        #   command = ["npm" "run" "dev"];
        #   manager = "web";
        #   env = {
        #     # Environment variables to set for your server
        #     PORT = "$PORT";
        #   };
        # };
      };
    };

    # Workspace lifecycle hooks
    workspace = {
      # Runs when a workspace is first created
      onCreate = {
        # Example: install JS dependencies from NPM
        # npm-install = "npm install";
      };
      # Runs when the workspace is (re)started
      onStart = {
        # Example: start a background task to watch and re-build backend code
        # watch-backend = "npm run watch-backend";
      };
    };
  };
}

```

**Screenshots**

COMMAND LINE [0 USERS]

![cmd-line](https://github.com/user-attachments/assets/33b45ba9-feaf-44e7-ad60-c0f3935ebc3f)

OPENING PAGE

![localhost:3000](https://github.com/user-attachments/assets/2e70725a-1cb2-4215-aef1-ffc1f9eb9fa0)

AUTHENTICATION PAGE

![Screenshot 2024](https://github.com/user-attachments/assets/cf582efe-91e8-489f-aa94-35ac79622367)
