### ISSUE TITLE
How to enable registartions?

### ISSUE THREAD

**Issue by mtthidoteu** [Yooooomi/your_spotify#45]
Hello,
I have just started the containers (fresh installation), and I am now greeted with the login page. However, I am unable to create an account as "Registrations are disabled". How do I enable them?
Thanks

Edit; The message "Could not retrieve the global preferences of the application" appears when loading the client.
Here is my docker-compose:

```
version: "3"
services:
  app:
    image: yooooomi/your_spotify_server
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://api.spotify.domain.com # Port 8080 on reverse proxy
      - CLIENT_ENDPOINT=https://spotify.domain.com # Port 3000 on reverse proxy
      - SPOTIFY_PUBLIC=hidden
      - SPOTIFY_SECRET=hidden
      - CORS=http://web:3000
      #- CORS=all
      - MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
  mongo:
    image: mongo
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    environment:
      - API_ENDPOINT=http://app:8080

networks:
  default
  web:
    name: web
```

and In the spotify dev portal i've set the redirect URL to: `https://api.spotify.domain.com/oauth/etc/etc/etc`
