### ISSUE TITLE
Error 401 retrieving data after logging in with Spotify account

### ISSUE THREAD

**Issue by 11matt556** [Yooooomi/your_spotify#48]
Hi,

I feel like I must be missing something obvious but just can't figure it out. I am able to register an account and login. I then get the message to log in to Spotify, which I do. However, it kicks me back to the login screen. After logging in again do not see any stats. The F12 debug menu reports numerous 401 errors, and the settings page says my account is linked, but the "Spotify infos" panel could not retrieve any info.

I am using the configuration below

```

version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: express-mongo
    restart: always
    ports:
      - "2101:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://spotify.mydomain.com:2101 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://docker.lan:2100
      - SPOTIFY_PUBLIC=redacted
      - SPOTIFY_SECRET=redacted
      - CORS=all
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: web
    restart: always
    ports:
      - "2100:3000"
    environment:
      - API_ENDPOINT=http://spotify.mydomain.com:2101

```

Appreciate any help that van be provided.

errata:

I am port forwarding port 2101 to the docker host using pfsense. The client is only accessible locally, either directly at docker.lan:2100 (the docker host) or via an nginx reverse proxy at spotify.lan. I can also access it locally usually the public domain. 

I have tried unlinking my Spotify account, relogging, and checking if accessing using any of the above methods makes a difference, but it does not seem to matter. I just can't get it to pull in the data.
