### ISSUE TITLE
Log in page is blank

### ISSUE THREAD

**Issue by RhykerWells** [Yooooomi/your_spotify#482]
**Describe the bug**

Attempting to move the api backend to a path of the main url for convienience, after getting my reverse proxy to work, the login button redirects to `/api/oauth/spotify`. Not `/api/oauth/spotify/callback` and the page is completely blank/black. Manually setting my URL to include `/callback` doesn't affect this whatsoever.

Current docker compose
```yaml
services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8086:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://spotify.rhykerw.com/api # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: https://spotify.rhykerw.com
      SPOTIFY_PUBLIC: XXX1
      SPOTIFY_SECRET: XXX2
  mongo:
    container_name: mongo
    image: mongo:4.4.18
    volumes:
      - /home/rhyker/docker/spotify:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "8087:3000"
    environment:
      API_ENDPOINT: https://spotify.rhykerw.com/api
```

Reverse proxy config (NGINX Proxy Manager. Manually edited file)
```
# ------------------------------------------------------------
# spotify.rhykerw.com
# ------------------------------------------------------------


map $scheme $hsts_header {
    https   "max-age=63072000; preload";
}

server {
  set $forward_scheme http;
  set $server         "rhykerw";
  set $port           8087;

  listen 80;
listen [::]:80;

  server_name spotify.rhykerw.com;
http2 off;

proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
proxy_http_version 1.1;

  access_log /data/logs/proxy-host-9_access.log proxy;
  error_log /data/logs/proxy-host-9_error.log warn;

  location / {

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;


    # Proxy!
    include conf.d/include/proxy.conf;
  }


  # Custom
  include /data/nginx/custom/server_proxy[.]conf;


  location /api {
    set $upstream_port 8086;
    proxy_pass $forward_scheme://$server:$upstream_port;
  }
}
```

Spotify developer dashboard
![Image](https://github.com/user-attachments/assets/43ea2969-a84a-4442-bcc5-e59c8a03596a)

It's worth noting that up until I attempted to move to the `/api` path of `spotify.rhykerw.com` for the back-end, everything worked smoothly
