### ISSUE TITLE
MongoDB not starting, backend cannot connect

### ISSUE THREAD

**Issue by mzfr** [Yooooomi/your_spotify#49]
```yaml
version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: express-mongo
    restart: always
    ports:
      - "9080:9080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.1.109:9080 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://192.168.1.109:3000
      - SPOTIFY_PUBLIC=<PUBLIC_KEY_HERE>
      - SPOTIFY_SECRET=<MY_SECRET_HERE>
        #- CORS=http://192.168.1.109:3000,http://192.168.1.109:3001
      - CORS=all
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://192.168.1.109:9080
```

This is my `docker-compose.yml` file. In the `Redirect URI` I've added `http://192.168.1.109:9080/oauth/spotify/callback`.

* Do I need to use the credentials of my Spotify account or are there any other?

Also, I noticed the following error when I ran `sudo docker logs express-mongo`

```TraceBack
2021-09-05T16:09:22.952Z [debug]: Trying to connect to database
/app/node_modules/mongoose/lib/connection.js:845
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:845:32)
    at /app/node_modules/mongoose/lib/index.js:348:10
    at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1152:10)
    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:347:20)
    at connect (/app/src/database/index.js:13:33)
    at MongoDbStore.load (/app/src/migrations.js:8:11)
    at loadMigrationsIntoSet (/app/node_modules/migrate/lib/load-migrations.js:25:9)
    at Function.exports.load (/app/node_modules/migrate/index.js:53:3)
    at Object.<anonymous> (/app/src/migrations.js:31:9)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        error: Error: getaddrinfo ENOTFOUND mongo
            at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:69:26) {
          name: 'MongoNetworkError'
        },
        roundTripTime: -1,
        lastUpdateTime: 32330811,
        lastWriteDate: null,
        opTime: null,
        type: 'Unknown',
        topologyVersion: undefined,
        minWireVersion: 0,
        maxWireVersion: 0,
        hosts: [],
        passives: [],
        arbiters: [],
        tags: []
      }
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.5
$ node ./src/migrations.js
2021-09-05T16:09:56.473Z [debug]: Trying to connect to database
```
