### ISSUE TITLE
MongoServerError: PlanExecutor error during aggregation :: caused by :: $push used too much memory and cannot spill to disk. Memory limit: 104857600 bytes

### ISSUE THREAD

**Issue by webysther** [Yooooomi/your_spotify#499]
**Describe the bug**

Error when acessing the 'Longest sessions' when for 10 years historical data with this amount of data:

![Image](https://github.com/user-attachments/assets/c5b9ea9e-2519-43d4-8570-41ee5b1ce2fa)

**Additional context**

```yml
services:
  spotify:
    image: lscr.io/linuxserver/your_spotify:1.12.0
    container_name: app-spotify
    env_file: ../your-spotify/.env
    networks:
      - your-spotify
      - your-spotify-db
    ports:
      - 680:80
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: db-mongo-spotify
    networks:
      - your-spotify-db
    volumes:
      - db:/data/db
    labels:
      wud.watch: false
    restart: unless-stopped

volumes:
  db:
    name: "$STACK-config"
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.1,rw"
      device: ":/volume1/docker/$STACK/db"

networks:
  your-spotify:
    name: your-spotify
  your-spotify-db:
    name: your-spotify-db
```

**Screenshots**

![Image](https://github.com/user-attachments/assets/5832e368-684d-4627-8f66-586650e9c1d9)

**Shared link**

If you don't mind, you can add a Shared link to this issue by clicking **Share this page** on your YourSpotify application so that I can identify the issue quicker.
