### ISSUE TITLE
Need https to pass Spotifys new security requirements

### ISSUE THREAD

**Issue by Yang-Richard** [Yooooomi/your_spotify#512]
Spotify recently increased the security requirements for application developers using the Spotify API. Specifically, cant use localhost or http anymore in the redirect URI.

https://developer.spotify.com/blog/2025-02-12-increasing-the-security-requirements-for-integrating-with-spotify

Current setup on Ubuntu 24.04 following the default docker setup results in the following error when attempting to login: 

INVALID_CLIENT: Insecure redirect URI

**Comment by DerHerrGammler** [comment]
You can use 127.0.0.1 instead of localhost and spotify is fine with it as redirect url

**Comment by Helmi4655** [comment]
Having the same Problem, anyone knows an Solution for this?

INVALID_CLIENT: Insecure redirect URI

![Image](https://github.com/user-attachments/assets/67162046-1082-4b87-89b7-2cd1daa33667)

https://[accounts.spotify.com/authorize?client_id=4fd5bba109c54a0383f5789705022a51&response_type=code&redirect_uri=http%3A%2F%2F192.168.178.87%3A8080%2Foauth%2Fspotify%2Fcallback&state=rtb03Wlvjy39XrnvL7kXn61y_xHlxl0bzN_t9ctQCrQ&scope=user-read-private+user-read-email+user-read-recently-played+user-modify-playback-state+playlist-modify-private+playlist-modify-public](https://accounts.spotify.com/authorize?client_id=4fd5bba109c54a0383f5789705022a51&response_type=code&redirect_uri=http%3A%2F%2F192.168.178.87%3A8080%2Foauth%2Fspotify%2Fcallback&state=rtb03Wlvjy39XrnvL7kXn61y_xHlxl0bzN_t9ctQCrQ&scope=user-read-private+user-read-email+user-read-recently-played+user-modify-playback-state+playlist-modify-private+playlist-modify-public)

Kind regards

**Comment by Wemmy0** [comment]
> You can use 127.0.0.1 instead of localhost and spotify is fine with it as redirect url

This workaround works. You need to find and replace `localhost` to `127.0.0.1` in docker-compose.yml too though.
For example:
```yml
services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://127.0.0.1:8080 # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: http://127.0.0.1:3000
      SPOTIFY_PUBLIC: ${SPOTIFY_PUBLIC}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://127.0.0.1:8080
```

**Comment by MelanX** [comment]
I have this:
```yaml
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - 3081:8080

    links:
      - mongo

    depends_on:
      - mongo

    environment:
      API_ENDPOINT: http://192.168.178.77:3081
      CLIENT_ENDPOINT: http://192.168.178.77:3080
      SPOTIFY_PUBLIC: <key> # Spotify DEV Public
      SPOTIFY_SECRET: <key> # Spotify DEV Secret
      
  mongo:
    container_name: mongo
    image: mongo:6 
    volumes:
      - /docker/your_spotify/DB:/data/db


  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - 3080:3000

    environment:
      API_ENDPOINT: http://192.168.178.77:3081
```

What should I do in the Spotify redirect uris? I did all of these:

![Image](https://github.com/user-attachments/assets/2d8fa2ae-dd2f-41a0-b594-755c9def24ba)

I'm so frustrated. I really want to use this and I have no idea how. I want to use Docker but I can't get it running.

**Comment by Wemmy0** [comment]
Yeah, I'm gonna be honest, this was a little annoying to get set up. A few things:

- When reloading the web interface, press shift + click the reload button
- Don't use docker compose restart​, you must docker compose down​ then docker compose up -d​
- Have a go with my docker-compose.yml:

```yml
services:
server:
image: yooooomi/your_spotify_server
restart: always
ports:
- "127.0.0.1:8080:8080"
links:
- mongo
depends_on:
- mongo
environment:
API_ENDPOINT: http://127.0.0.1:8080
CLIENT_ENDPOINT: http://127.0.0.1:3000
SPOTIFY_PUBLIC: ${SPOTIFY_PUBLIC}
SPOTIFY_SECRET: ${SPOTIFY_SECRET}
mongo:
container_name: mongo
image: mongo:6
volumes:
- ./your_spotify_db:/data/db

web:
image: yooooomi/your_spotify_client
restart: always
ports:
- "127.0.0.1:3000:3000"
environment: API_ENDPOINT: http://127.0.0.1:8080
```

I have it setup so it's only accessable on my local machine running the docker container and NOT other devices on the same local network. Hopeful it works now for you.

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by MelanX** [comment]
Thank you but sadly, I want to have it on my home server. I could try to set it up on my machine and then transfer the credentials to the container on my home server. In that case, you would be pretty helpful, sure. Thank you :)

**Comment by preethamvishy** [comment]
I have the same issue. 
1. If I pass an endpoint URL without HTTPS, I get `INVALID_CLIENT: Insecure redirect URI` from Spotify. 
2. Instead, if I modify the Spotify URL (`https://accounts.spotify.com/authorize?....`) to change the `redirect_uri` to `https` (along with adding `https:*` to the Redirect URIs to the Spotify app), then I run into `(failed)net::ERR_SSL_PROTOCOL_ERROR` for the `/oauth/spotify/callback` call because it doesn't support HTTPS.

It would be good to have `https` support with docker compose without having to set up certificates (and a proxy). If not, it would be nice to have support for passing in the `state` and `code` from the Spotify callback to the server as env variables to work around the need for for the server/client to be run with `https`

**Comment by SleepySpeller** [comment]
Has anyone found a solution?
Currently, I have a small server on 192.168.100.5, and I'm getting `INVALID_CLIENT: Insecure redirect URI`.
My Spotify dashboard looks like this:

<img width="497" height="748" alt="Image" src="https://github.com/user-attachments/assets/3476d9ad-47ef-432b-aec7-60f9c5ec73f2" />

and docker-compose like this:

```
version: "3.8"
services:
  mongo:
    image: mongo:4.4
    container_name: yourspotify_mongo
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db

  server:
    image: yooooomi/your_spotify_server
    container_name: yourspotify_server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
      - SPOTIFY_PUBLIC=${SPOTIFY_PUBLIC}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - API_ENDPOINT=${API_URL}
      - CLIENT_ENDPOINT=${CLIENT_URL}
      - TZ=${TZ}
      - CORS=${CLIENT_URL}
    depends_on:
      - mongo

  web:
    image: yooooomi/your_spotify_client
    container_name: yourspotify_client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=${API_URL}
```
and .env:
```
SPOTIFY_PUBLIC=...
SPOTIFY_SECRET=...
API_URL=http://192.168.100.5:8080
CLIENT_URL=http://192.168.100.5:3000
TZ=Europe/Sarajevo
```

I have tried pretty much everything, from creating a new app on Spotify, to the linuxserver image, checking if the server is sending data to Spotify correctly, and everything in-between.

**Comment by nonvenomous** [comment]
I wanted to locally develop on the project but ran into some issues as well. Here the workaround I picked as a reference.

https://github.com/nonvenomous/your_spotify_fork/commit/e62fca54da970d50c1206a308cfbdce0f6ea27b9 (EDIT: not needed anymore due to https://github.com/Yooooomi/your_spotify/commit/5066402d6b6953400989c4b4bf338424f7211769)

- spotify redirect URI: `http://127.0.0.1:8080/oauth/spotify/callback`

Besides the changes in the commit I only have changed the `docker-compose-personal.yml` to get `sh dev.sh` and oauth to work.

```yaml
# docker-compose-personal.yml
services:
  app:
    environment:
      API_ENDPOINT: http://127.0.0.1:8080
      CLIENT_ENDPOINT: http://127.0.0.1:3000
      SPOTIFY_PUBLIC: __public__
      SPOTIFY_SECRET: __secret__
  web:
    environment:
      NODE_ENV: development
      API_ENDPOINT: http://127.0.0.1:8080
```
