### ISSUE TITLE
Changed the URL to a public https URL and still recongising local 192.168 IP

### ISSUE THREAD

**Issue by Coysh** [Yooooomi/your_spotify#520]
**Describe the bug**

To get around the HTTPS issues with spotify I set up https://myspotify.domain.com and https://myspotify-api.domain.com with SSL certs.

I've changed my compose.yaml to the below, but even after multiple restarts I get a below error, referencing the local IP:

```
xhr.js:195 Mixed Content: The page at 'https://myspotify.domain.com/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://192.168.1.103:8080/me'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ xhr.js:195
thunk.ts:24 nh
(anonymous) @ thunk.ts:24
xhr.js:195 Mixed Content: The page at 'https://myspotify.domain.com/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://192.168.1.103:8080/global/preferences'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ xhr.js:195
thunk.ts:28 nh
(anonymous) @ thunk.ts:28
```

![Image](https://github.com/user-attachments/assets/069c8765-4567-44e5-aa18-ec10530a052d)

**Expected behavior**

Login

**Additional context**

```
services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://api-myspotify.domain.com
      CLIENT_ENDPOINT: https://myspotify.domain.com
      SPOTIFY_PUBLIC: XXX
      SPOTIFY_SECRET: XXX
      CORS: https://myspotify-api.domain.com,https://myspotify.domain.com,http://192.168.1.103:8080,http://192.168.1.103:3001
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db
  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - 3001:3000
    environment:
      API_ENDPOINT: https://api-myspotify.domain.com
      CORS: https://myspotify-api.domain.com,https://myspotify.domain.com,http://192.168.1.103:8080,http://192.168.1.103:3001
networks: {}
```

**Screenshots**

**Shared link**

If you don't mind, you can add a Shared link to this issue by clicking **Share this page** on your YourSpotify application so that I can identify the issue quicker.
