### ISSUE TITLE
OAuth Redirect URL is Malformed — Frontend Constructs Invalid Callback Path

### ISSUE THREAD

**Issue by mahmudurrahmanlabib** [Yooooomi/your_spotify#527]
**Describe the bug**
After clicking the "Login with Spotify" button, the app redirects to an incorrect and malformed URL:

```
https://cspotify.xynoslab.com/your_spotify_backend/oauth/spotify/callback/api/oauth/spotify
```

This breaks the login flow and prevents successful authentication. It seems the frontend is constructing the redirect URI incorrectly — possibly appending multiple path segments.

---

**Expected behavior**
The redirect after login should point to a valid and Spotify-registered OAuth callback URL, like:

```
https://cspotify.xynoslab.com/api/oauth/spotify/callback
```

This should then complete the OAuth flow and return the user to the frontend in a logged-in state.

---

**Additional context**

**Docker Compose:**

```yaml
services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://cspotify.xynoslab.com
      CLIENT_ENDPOINT: https://cspotify.xynoslab.com
      SPOTIFY_PUBLIC: **********************************
      SPOTIFY_SECRET: ***************************************
      CORS: i-want-a-security-vulnerability-and-want-to-allow-all-origins

  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3087:3000"
    environment:
      API_ENDPOINT: https://cspotify.xynoslab.com
```

**Reverse Proxy Setup (Caddy):**
The domain `https://cspotify.xynoslab.com` is configured in Caddy to route:

```caddyfile
cspotify.xynoslab.com {
    encode gzip
    tls your@email.com

    # Route /api/* to the backend (YourSpotify Server)
    reverse_proxy /api/* localhost:8080

    # Everything else to the frontend (YourSpotify Client)
    reverse_proxy localhost:3087
}
```

**Spotify Dashboard Redirect URI:**
Configured with:

```
https://cspotify.xynoslab.com/api/oauth/spotify/callback
```
