### ISSUE TITLE
How to setup endpoints

### ISSUE THREAD

**Issue by D3rJust1n** [Yooooomi/your_spotify#530]
I have a question about how to configure the endpoints correctly
I use caddy and cloudflare tunnel. When I try to log in I get a message that something is wrong with the API endpoint

I am attaching my compose, my excerpt from my caddyfile and the screenshot of the login attempt

```yml
services:
  server:
    image: yooooomi/your_spotify_server
    container_name: your-spotify-server
    restart: always
    networks:
      - cloudflared_default
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://spoti.d3r.eu # This MUST be included as a valid URL in the spotify dashboard
      CLIENT_ENDPOINT: https://spoti.d3r.eu
      SPOTIFY_PUBLIC: ID
      SPOTIFY_SECRET: Secret
      CORS: http://localhost:3000,http://localhost:3001 # "i-want-a-security-vulnerability-and-want-to-allow-all-origins" if you want to allow every origin

  mongo:
    container_name: your-spotify-mongo
    image: mongo:6
    networks:
      - cloudflared_default
    restart: always
    volumes:
      - ./your-spotify-db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: your-spotify-web
    networks:
      - cloudflared_default
    restart: always
    environment:
      API_ENDPOINT: https://spoti.d3r.eu

networks:
  cloudflared_default:
    external: true

```

```Caddyfile
spoti.d3r.eu {
	reverse_proxy your-spotify-web:3000
}
```

![Image](https://github.com/user-attachments/assets/8569d272-e56a-4415-848b-fe3161072110)

**Comment by D3rJust1n** [comment]
I have now set it up again with this config, I could then also give spotify access but then I end up in the loop you can see in the video

```yml
services:
  server:
    image: yooooomi/your_spotify_server
    container_name: your-spotify-server
    restart: always
    networks:
      - cloudflared_default
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://spoti-api.d3r.eu # This MUST be included as a valid URL in the spotify dashboard
      CLIENT_ENDPOINT: https://spoti.d3r.eu
      SPOTIFY_PUBLIC: PUBLIC
      SPOTIFY_SECRET: SECRET
      CORS: http://localhost:3000,http://localhost:3001 # "i-want-a-security-vulnerability-and-want-to-allow-all-origins" if you want to allow every origin

  mongo:
    container_name: mongo
    image: mongo:6
    restart: always
    networks:
      - cloudflared_default
    volumes:
      - ./your-spotify-db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: your-spotify-web
    restart: always
    networks:
      - cloudflared_default
    environment:
      API_ENDPOINT: https://spoti-api.d3r.eu

networks:
  cloudflared_default:
    external: true

```

```Caddyfile
spoti.d3r.eu {
	reverse_proxy your-spotify-web:3000
}

spoti-api.d3r.eu {
	reverse_proxy your-spotify-server:8080
}
```


https://github.com/user-attachments/assets/845852f5-d4cd-4873-859d-290ca75dfd46
