### ISSUE TITLE
[Question] Default Login Credentials

### ISSUE THREAD

**Issue by Kuuchuu** [Yooooomi/your_spotify#57]
I might be missing something obvious, but I cannot locate the default credentials. Registrations are disabled by default, so I'm unable to create an account. Are there environment variables that can be used to specify admin account info?
Thanks

**Comment by Yooooomi** [comment]
Hello!
If the registrations are off by default, it might be because the client cannot reach the server, and disabled registration. Please join here the docker-compose file you're using so we can troubleshoot this :)

**Comment by Kuuchuu** [comment]
```
version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: your-spotify-server
    restart: always
    ports:
      - "7685:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotify.z****.io/api # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=https://spotify.z****.io
      - SPOTIFY_PUBLIC=****************************************ac28
      - SPOTIFY_SECRET=****************************************a3e0
      - CORS=all
      #- CORS=all
      - MONGO_ENDPOINT=mongodb://your-spotify-mongo:27017/your_spotify
  mongo:
    container_name: your-spotify-mongo
    image: mongo
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: your-spotify-web
    restart: always
    ports:
      - "7684:3000"
    environment:
      - API_ENDPOINT=https://spotify.z****.io/api
```

**Comment by Yooooomi** [comment]
Everything seems good in your config file. Can you please share a screenshot of the errors in your chrome console and the configuration of your reverse proxy please 🙂

**Comment by Kuuchuu** [comment]
@Yooooomi Here is my SWAG Nginx proxy conf for the containers:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name spotify.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.1.220;
        set $upstream_port 7684;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_max_temp_file_size 2048m;
    }

    location /api/ {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.1.220;
        set $upstream_port 7685;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_max_temp_file_size 2048m;
    }

}
```
Thanks for checking over this stuff, I appreciate it!

**Comment by Yooooomi** [comment]
The client max body size set to 0 is a bit weird to me since it prevents the client from sending anything to the backend if I understand correctly.
Also, I added an extra slash at the end of the proxy pass in my configuration, that you can see in #55.
Check those two ideas and if it's not working please send the errors you're getting frontend 🙂
Good luck

**Comment by Kuuchuu** [comment]
@Yooooomi The client_max_body_size 0 disables checking of client request body size, but really I don't need it here and it's a bad habit of mine to include it.  I also didn't need the proxy_max_temp_file_size for this app, so I removed that as well.
Adding a "/" after the port on the "/api/" location did get the web client to see the api! Adding a "/" after the port on the root location, "/", made the web client fail to load, it only showed a white screen. I also added a "/" to the end of the URL for the API_ENDPOINT and CLIENT_ENDPOINT environment variables.

Now, my new issue is the same as #56
The login screen appears for a quick moment, then changes blue. I opened dev tools and refreshed the page and saw that everything contained in `<div id="root"></div>`was initially there when the site first loaded, then it all vanished when the screen turned blue. The docker container logs don't seem to show anything useful, with the server container being the only one who's logs change upon site access:
```
2021-12-06T08:38:27.383Z [info]: Starting loop for 0 users
GET / 304 0.271 ms - -
GET / 304 0.198 ms - -
GET / 304 0.212 ms - -
GET / 304 0.214 ms - -
GET / 304 0.198 ms - -
GET / 304 0.278 ms - -
2021-12-06T08:40:27.387Z [info]: Starting loop for 0 users
GET / 200 0.316 ms - 7
GET / 200 0.163 ms - 7
GET / 200 0.199 ms - 7
```
Dev tools however did show an error message in the console when the site loaded:
```
react-dom.production.min.js:216 TypeError: i.map is not a function
    at xn (index.js:95)
    at oa (react-dom.production.min.js:157)
    at Ua (react-dom.production.min.js:180)
    at $c (react-dom.production.min.js:269)
    at Cu (react-dom.production.min.js:250)
    at ku (react-dom.production.min.js:250)
    at Eu (react-dom.production.min.js:250)
    at mu (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
cc @ react-dom.production.min.js:216
index.js:32 TypeError: i.map is not a function
    at xn (index.js:95)
    at oa (react-dom.production.min.js:157)
    at Ua (react-dom.production.min.js:180)
    at $c (react-dom.production.min.js:269)
    at Cu (react-dom.production.min.js:250)
    at ku (react-dom.production.min.js:250)
    at Eu (react-dom.production.min.js:250)
    at mu (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
(anonymous) @ index.js:32
```
Thanks again

**Comment by Kuuchuu** [comment]
Here is the curl returned when run against my domain:
```
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="Web Application for your spotify"/><link rel="apple-touch-icon" href="/logo192.png"/><link rel="manifest" href="/manifest.json"/><script src="/variables-final.js"></script><title>Your Spotify</title><link href="/static/css/main.a96467d3.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(e){function t(t){for(var n,l,i=t[0],f=t[1],a=t[2],p=0,s=[];p<i.length;p++)l=i[p],Object.prototype.hasOwnProperty.call(o,l)&&o[l]&&s.push(o[l][0]),o[l]=0;for(n in f)Object.prototype.hasOwnProperty.call(f,n)&&(e[n]=f[n]);for(c&&c(t);s.length;)s.shift()();return u.push.apply(u,a||[]),r()}function r(){for(var e,t=0;t<u.length;t++){for(var r=u[t],n=!0,i=1;i<r.length;i++){var f=r[i];0!==o[f]&&(n=!1)}n&&(u.splice(t--,1),e=l(l.s=r[0]))}return e}var n={},o={1:0},u=[];function l(t){if(n[t])return n[t].exports;var r=n[t]={i:t,l:!1,exports:{}};return e[t].call(r.exports,r,r.exports,l),r.l=!0,r.exports}l.m=e,l.c=n,l.d=function(e,t,r){l.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},l.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},l.t=function(e,t){if(1&t&&(e=l(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(l.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var n in e)l.d(r,n,function(t){return e[t]}.bind(null,n));return r},l.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return l.d(t,"a",t),t},l.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},l.p="/";var i=this.webpackJsonpclient=this.webpackJsonpclient||[],f=i.push.bind(i);i.push=t,i=i.slice();for(var a=0;a<i.length;a++)t(i[a]);var c=f;r()}([])</script><script src="/static/js/2.202431e0.chunk.js"></script><script src="/static/js/main.683a6e3c.chunk.js"></script></body></html>
```
The api domain does return "Hello !"

**Comment by Yooooomi** [comment]
Hello, I'm glad you're trying hard to get it working :)
You should not need to append a trailing / at the end of the env variables for the endpoints, since the API script adds routes such as `/user`, so concatenating yours with the API results in `https://domain.com//user`.

As in #56 , the search bar is receiving the front end instead of the backend response, then it tries to parse an html page as a json response, that's why its not working.
I'm going to try hosting it the way you do to see if I'm having the same issue.
Feel free to add me on discord as `Marvin the Martian#8336` so that we can fix this faster :)

**Comment by Kuuchuu** [comment]
Hey @Yooooomi sorry for the very late reply, work got fairly busy. I made further changes to both my docker-compose.yml and my NGINX conf file, but the results are the same. I went ahead and added you on discord. Thanks for the help

**Comment by Yooooomi** [comment]
I got no response from you on discord, is your issue still up to date ?

**Comment by smikkelbakje** [comment]
i have exacly the same problem this is my console log 
![image](https://user-images.githubusercontent.com/59176120/154442329-07a94c36-71b7-4fbe-9d56-57bdca8f68c2.png)

**Comment by Yooooomi** [comment]
@smikkelbakje it seems that your browser is sending a header that is not allowed. Can you try clearing the cookies of your browser on localhost:3000 and try again?

https://stackoverflow.com/questions/38589944/angular2-x-xsrf-token-is-not-allowed-by-access-control-allow-headers

**Comment by smikkelbakje** [comment]
yep that worked, there where still some cookies from other projects 
thanks

**Comment by esturniolo** [comment]
Hi!!
Same problem here!

I can't  create new users.

Here are my compose and reverse proxy config file


COMPOSE:

```
version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: ${CONTAINERNAME}-express-mongo
    restart: always
#    ports:
#      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://172.20.0.50:8080 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://172.20.0.49:3000
      - SPOTIFY_PUBLIC=magicNumber
      - SPOTIFY_SECRET=aMoreMagicNumber
      #- CORS=http://172.20.0.50:3000,http://172.20.0.50:3001
      - CORS=all
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
      #- MAX_IMPORT_CACHE_SIZE=100000 # Number of items cached during import of past history
      - TZ=${TZ} # Only affects read requests, write are in UTC time
    networks:
      myNetwork:
        ipv4_address: 172.20.0.50      
  mongo:
    container_name: ${CONTAINERNAME}-mongo
    image: mongo
    volumes:
      - ${CONTAINERDIR}/config/db:/data/db
    networks:
      myNetwork:
        ipv4_address: 172.20.0.51 
  web:
    image: yooooomi/your_spotify_client
    container_name: ${CONTAINERNAME}-web
    restart: always
#    ports:
#      - "3000:3000"
    environment:
      - API_ENDPOINT=http://172.20.0.50:8080
    networks:
      myNetwork:
        ipv4_address: 172.20.0.49
networks:
  myNetwork:
    external: true
```

Nginx conf file

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name spotify.mySuperSecret.domain;

    client_max_body_size 10M;

    gzip            on;
    gzip_proxied    any;
    gzip_types      text/plain text/css text/js application/xml application/json application/x-javascript application/javascript;
    
    ssl_certificate /etc/letsencrypt/live/mySuperSecret.domain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mySuperSecret.domain/privkey.pem;
    
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256:EECDH+CHACHA20:EECDH+AESGCM:EECDH+AES;

    add_header Strict-Transport-Security "max-age=15552000";

    location / {
        proxy_pass       http://172.20.0.49:3000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Scheme	$scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Ssl on;
        # proxy_set_header Upgrade $http_upgrade;
        # proxy_set_header Connection "upgrade";
        # proxy_http_version 1.1;
        proxy_redirect   off;
    }
}
```

Any idea? 
Any help will be appreciated.

thanks!!
