### ISSUE TITLE
Getting CORS errors

### ISSUE THREAD

**Issue by wreuel** [Yooooomi/your_spotify#66]
Hi guys, I have tried a lot of versions and went on some issues but I still getting the CORS error and so being unable to create user or even login.

I using a version of docker-compose I found here https://github.com/Yooooomi/your_spotify/issues/39#issuecomment-846377239

as follow:

```
version: "3"

services:
  your_spotify:
    image: yooooomi/your_spotify_server
    container_name: your_spotify
    restart: always
    ports:
      - "8085:8080"
    links:
      - your_spotify_mongo
    depends_on:
      - your_spotify_mongo
    environment:
      - API_ENDPOINT=http://192.168.0.30:8085 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://192.168.0.30:8086
      - SPOTIFY_PUBLIC={myid}
      - SPOTIFY_SECRET={mysecret}
      # - CORS=http://192.168.1.1:4000,http://localhost:4001
      - CORS=all
      - MONGO_ENDPOINT=mongodb://your_spotify_mongo:27017/your_spotify
  your_spotify_mongo:
    container_name: your_spotify_mongo
    image: mongo
    logging:
      driver: none
    volumes:
      - /srv/dev-disk-by-uuid-2a99a502-3631-497e-be98-36c6945b88af/docker/appdata/spotify/db:/data/db
  your_spotify_web:
    image: yooooomi/your_spotify_client
    container_name: your_spotify_web
    restart: always
    ports:
      - "8086:3000"
    environment:
      - API_ENDPOINT=http://192.168.0.30:8085
```

But always getting the CORS as on this image
![image](https://user-images.githubusercontent.com/6828665/149338733-40bfd7c8-e035-442d-9206-0a946cfb6ac4.png)
