### ISSUE TITLE
Client can't connect to API

### ISSUE THREAD

**Issue by gustavohw** [Yooooomi/your_spotify#7]
Hi, maybe I'm missing something here, but it seems that I can't connect to the API endpoint, accessing the client it yields a 
``GET http://192.168.100.225:8080/me net::ERR_CONNECTION_REFUSED`` or similar errors of connection_refused.

This is my current section of `docker-compose.yml`:
```yml
  your-spotify-server:
   image: yooooomi/your_spotify_server
   container_name: your-spotify-server
   restart: unless-stopped
   ports:
      - 8080:8080
   links:
      - your-spotify-mongo
   depends_on:
      - your-spotify-mongo
   environment:
      - "API_ENDPOINT=http://192.168.100.225:8080"
      - "CLIENT_ENDPOINT=http://192.168.100.225:3000"
      - SPOTIFY_PUBLIC=###
      - SPOTIFY_SECRET=###
      - CORS=all

  your-spotify-mongo:
    container_name: your-spotify-mongo
    image: mongo
    volumes:
      - ${ROOT_DIR}/your-spotify:/data/db

  your-spotify-client:
    image: yooooomi/your_spotify_client
    container_name: your-spotify-client
    restart: unless-stopped
    environment:
      - "API_ENDPOINT=http://192.168.100.225:8080"
    ports:
      - 3000:3000
```

I tried using traefik as a proxy and seem to got to connect somehow but then had too much issues with CORS and `Access-Control-Allow-Origin` and `accessControlAllowCredentials`, so I put that on hold to try get it working without the proxy first.
