### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI when logging to Spotify

### ISSUE THREAD

**Issue by smikkelbakje** [Yooooomi/your_spotify#73]
![image](https://user-images.githubusercontent.com/59176120/154454919-06eeb39a-0326-45e9-b1d7-93b88db199ef.png)
![image](https://user-images.githubusercontent.com/59176120/154454923-d55489eb-34a4-4437-a94e-4be5c232b602.png)
i've entered the key and the secret in the docker-composer.yml but i get this error

https://accounts.spotify.com/authorize?response_type=code&client_id=public%20key&scope=user-read-private%20user-read-email%20user-read-recently-played%20user-modify-playback-state&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Foauth%2Fspotify%2Fcallback

this is the link

**Comment by Yooooomi** [comment]
Hello, this means the url you entered in the Spotify application you created is not the url of your backend. Please double check it :)

This should be something like 
`http://localhost:8000/oauth/spotify/callback`

**Comment by smikkelbakje** [comment]
```
version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: express-mongo
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://localhost:3000
      - SPOTIFY_PUBLIC=public key
      - SPOTIFY_SECRET= private secret
      - CORS=http://localhost:3000,http://localhost:3001
      #- CORS=all
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://localhost:8080
```
![image](https://user-images.githubusercontent.com/59176120/154459266-63f0a6c6-4bd9-4ef9-af3f-9229265cde7a.png)
