### ISSUE TITLE
Can't login nor create a new user after start a fresh container.

### ISSUE THREAD

**Issue by esturniolo** [Yooooomi/your_spotify#80]
Hi!!
The problem explains itself in the title.

I can't create new users.

Here are my compose and reverse proxy config file

**COMPOSE**:

```
version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: ${CONTAINERNAME}-express-mongo
    restart: always
#    ports:
#      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://172.20.0.50:8080 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://172.20.0.49:3000
      - SPOTIFY_PUBLIC=magicNumber
      - SPOTIFY_SECRET=aMoreMagicNumber
      #- CORS=http://172.20.0.50:3000,http://172.20.0.50:3001
      - CORS=all
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
      #- MAX_IMPORT_CACHE_SIZE=100000 # Number of items cached during import of past history
      - TZ=${TZ} # Only affects read requests, write are in UTC time
    networks:
      myNetwork:
        ipv4_address: 172.20.0.50      
  mongo:
    container_name: ${CONTAINERNAME}-mongo
    image: mongo
    volumes:
      - ${CONTAINERDIR}/config/db:/data/db
    networks:
      myNetwork:
        ipv4_address: 172.20.0.51 
  web:
    image: yooooomi/your_spotify_client
    container_name: ${CONTAINERNAME}-web
    restart: always
#    ports:
#      - "3000:3000"
    environment:
      - API_ENDPOINT=http://172.20.0.50:8080
    networks:
      myNetwork:
        ipv4_address: 172.20.0.49
networks:
  myNetwork:
    external: true

```

**Nginx conf file**

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name spotify.mySuperSecret.domain;

    client_max_body_size 10M;

    gzip            on;
    gzip_proxied    any;
    gzip_types      text/plain text/css text/js application/xml application/json application/x-javascript application/javascript;
    
    ssl_certificate /etc/letsencrypt/live/mySuperSecret.domain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mySuperSecret.domain/privkey.pem;
    
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256:EECDH+CHACHA20:EECDH+AESGCM:EECDH+AES;

    add_header Strict-Transport-Security "max-age=15552000";

    location / {
        proxy_pass       http://172.20.0.49:3000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Scheme	$scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Ssl on;
        # proxy_set_header Upgrade $http_upgrade;
        # proxy_set_header Connection "upgrade";
        # proxy_http_version 1.1;
        proxy_redirect   off;
    }
}

```

CONSOLE LOG (mysuper.domain/register)

```
Error: Request aborted
    exports createError.js:16
    onabort xhr.js:107
    exports xhr.js:102
    exports xhr.js:15
    exports dispatchRequest.js:58
    request Axios.js:112
    e Axios.js:136
    exports bind.js:9
    Yp api.ts:34
    nh api.ts:131
    e Redux
    c runtime.js:63
    _invoke runtime.js:294
    S runtime.js:119
    Babel 4
    Redux 8
    xy Wrapper.tsx:11
    zs React
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    D scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    6813 scheduler.production.min.js:12
    Webpack 10
[thunk.ts:20:14](https://spotify.appsen.casa/static/js/services/redux/modules/settings/thunk.ts)
    e Redux
    c runtime.js:63
    _invoke runtime.js:294
    S runtime.js:119
    Babel 6
    Redux 8
    xy Wrapper.tsx:11
    zs React
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    D scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    (Asíncrono: EventHandlerNonNull)
    6813 scheduler.production.min.js:12
    Webpack 10
Error: Request aborted
    exports createError.js:16
    onabort xhr.js:107
    exports xhr.js:102
    exports xhr.js:15
    exports dispatchRequest.js:58
    request Axios.js:112
    e Axios.js:136
    exports bind.js:9
    Yp api.ts:34
    eh api.ts:129
    e Redux
    c runtime.js:63
    _invoke runtime.js:294
    S runtime.js:119
    Babel 4
    Redux 7
    xy Wrapper.tsx:10
    zs React
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    D scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    6813 scheduler.production.min.js:12
    Webpack 10
[thunk.ts:62:12](https://spotify.appsen.casa/static/js/services/redux/modules/user/thunk.ts)
    e Redux
    c runtime.js:63
    _invoke runtime.js:294
    S runtime.js:119
    Babel 6
    Redux 7
    xy Wrapper.tsx:10
    zs React
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    D scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    (Asíncrono: EventHandlerNonNull)
    6813 scheduler.production.min.js:12
    Webpack 10
```

Any idea?
Any help will be appreciated.

thanks!!
