### ISSUE TITLE
Could not retrieve global preferences

### ISSUE THREAD

**Issue by Leyts** [Yooooomi/your_spotify#85]
Receiving the error "Could not retrieve global preferences" upon opening _http://**my_pi_ip**:3000_. I have _http://localhost:3000/oauth/spotify/callback_ and _http://localhost:8080/oauth/spotify/callback_ under _Redirect URIs_ in my Spotify Dashboard. Running in Docker on a Raspberry Pi 3 B+ (Pi Bullseye 64-bit) on my local network. I'm quite new to this so I might've missed something really obvious...

```
version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: express-mongo
    restart: unless-stopped
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://localhost:3000
      - SPOTIFY_PUBLIC=__my_client_id__
      - SPOTIFY_SECRET=__my_client_secret__
      - CORS=http://localhost:3000,http://localhost:3001
      #- CORS=all
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
      #- MAX_IMPORT_CACHE_SIZE=100000 # Number of items cached during import of past history
      - TIMEZONE=Europe/London # Only affects read requests, write are in UTC time
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://localhost:8080
```

**Comment by Yooooomi** [comment]
Hello!
If you're accessing the app from the computer while it's hosted on the pi, localhost won't work. What it will try to do is request your computer instead of the pi. You have to put the local IP address of the pi in the endpoints.

**Comment by Leyts** [comment]
> Hello! If you're accessing the app from the computer while it's hosted on the pi, localhost won't work. What it will try to do is request your computer instead of the pi. You have to put the local IP address of the pi in the endpoints.

Thanks for getting back to me so quick. Same error with the following _docker_compose_ and _Redirect URIs_ set to _http://192.168.0.50:3000/oauth/spotify/callback_ and _http://192.168.0.50:3000/oauth/spotify/callback_.

```
version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: express-mongo
    restart: unless-stopped
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.0.50:8080 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://192.168.0.50:3000
      - SPOTIFY_PUBLIC=__my_client_id__
      - SPOTIFY_SECRET=__my_client_secret__
      - CORS=http://192.168.0.50:3000,http://192.168.0.50:3001
      #- CORS=all
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
      #- MAX_IMPORT_CACHE_SIZE=100000 # Number of items cached during import of past history
      - TIMEZONE=Europe/London # Only affects read requests, write are in UTC time
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://192.168.0.50:8080
```
