### ISSUE TITLE
Reporting no new music for user

### ISSUE THREAD

**Issue by TheSpad** [Yooooomi/your_spotify#88]
**Describe the bug**
Initial import of history and first ~24 hours of use logged correctly but nothing has been recorded in the last ~8 hours despite several dozen tracks being played. Not running in a Private Session or anything like that. Have tried the Relog To Spotify option but that hasn't changed anything.

**Expected behavior**
All play history should be recorded

**Additional context**
Pulled the latest images ~1 hour ago.
```yml
services:
  your_spotify_server:
    image: docker.io/yooooomi/your_spotify_server:latest
    container_name: your_spotify_server
    environment:
      - API_ENDPOINT=https://spotify_server.domain.com
      - CLIENT_ENDPOINT=https://spotify.domain.com
      - SPOTIFY_PUBLIC=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_SECRET=${SPOTIFY_CLIENT_SECRET}
      - CORS=all
      - MONGO_ENDPOINT=mongodb://your_spotify_db:27017/your_spotify
      - TIMEZONE=Europe/London
    networks:
      - private
      - proxy
    restart: unless-stopped
    depends_on:
      - your_spotify_db
    labels:
      - traefik.enable=true
      - traefik.http.routers.your_spotify_server-https.rule=Host(`spotify_server.domain.com`)
      - traefik.http.routers.your_spotify_server-https.entrypoints=https
      - traefik.http.routers.your_spotify_server-https.service=your_spotify_server-svc
      - traefik.http.routers.your_spotify_server-https.middlewares=middleware-ipwhitelist@file
      - traefik.http.services.your_spotify_server-svc.loadbalancer.server.port=8080      

  your_spotify_client:
    image: docker.io/yooooomi/your_spotify_client:latest
    container_name: your_spotify_client
    environment:
      - API_ENDPOINT=https://spotify_server.domain.com
    networks:
      - private
      - proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.your_spotify-https.rule=Host(`spotify.domain.com`)
      - traefik.http.routers.your_spotify-https.entrypoints=https
      - traefik.http.routers.your_spotify-https.service=your_spotify-svc
      - traefik.http.routers.your_spotify-https.middlewares=middleware-ipwhitelist@file
      - traefik.http.services.your_spotify-svc.loadbalancer.server.port=3000

  your_spotify_db:
    container_name: your_spotify_db
    image: docker.io/mongo:4
    volumes:
      - db:/data/db
    tmpfs:
      - /data/configdb      
    networks:
      - private
    restart: unless-stopped

volumes:
  db:

networks:
  proxy:
    external: true
  private:
```
Logs just repeat the below every 2 minutes
```
2022-02-21T16:35:06.290506107Z [info]  Starting loop for 1 users
2022-02-21T16:35:06.292530966Z [info]  Refreshing songs for <my user>
2022-02-21T16:35:06.408260974Z [info]  User has no new music
```
