### ISSUE TITLE
Caddy2 reverse proxy

### ISSUE THREAD

**Issue by the-citizenfour** [Yooooomi/your_spotify#93]
Hi

I've wanted to make the Spotify stats page public with the Caddy2 reverse proxy.

I've got the following error by setting it up:
![image](https://user-images.githubusercontent.com/69928057/155897617-8bd4bd63-7e7d-4654-97be-f6712e2424e1.png)

What parameters do I have to change, to make it work?

Thanks in advance

**Comment by Yooooomi** [comment]
Hello!
Can you please share the config filers you're using to host this application?
Thanks :)

**Comment by the-citizenfour** [comment]
Sure

My Caddyfile is pretty simple:
`***.duckdns.org: 443 {
    reverse_proxy localhost:3000
}`

**Comment by Yooooomi** [comment]
Can you please also share your docker-compose file(s) you're using?

**Comment by the-citizenfour** [comment]
The Caddy server runs directly on the server and not in Docker, and the Spotify file is:

`version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: express-mongo
    restart: always
    ports:
      - "11223:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.1.169:11223 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://192.168.1.169:3000
      - SPOTIFY_PUBLIC=c65d307da7d748b8a24f946252a9d1b3
      - SPOTIFY_SECRET=6a4928e7651d4adfa7541679bb8e3e90
      #- CORS=http://localhost:3000,http://localhost:3001
      - CORS=all
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
      #- MAX_IMPORT_CACHE_SIZE=100000 # Number of items cached during import of past history
      #- TIMEZONE=Europe/Paris # Only affects read requests, write are in UTC time
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://192.168.1.169:11223`

**Comment by Yooooomi** [comment]
You need to reverse proxy the backend too with its own subdomain. Also I think you have to set the ENDPOINT variables to the public endpoints, not the local ones.
Your API_ENDPOINT should then theorically be spotify-server.duckdns.org and the CLIENT_ENDPOINT spotify.duckdns.org

**Comment by the-citizenfour** [comment]
Thanks, I'll give that a try, but need some time to set it up.

I will let you know if it worked. 👍🏻

**Comment by the-citizenfour** [comment]
I've tried to deploy it with 2 subdomains, but at the moment I still get an error.

```
version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: express-mongo2
    restart: always
    ports:
      - "11224:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotifybackend.duckdns.org # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=https://marcspotify.duckdns.org
      - SPOTIFY_PUBLIC=c65d307da7d748b8a24f946252a9d1b3
      - SPOTIFY_SECRET=***
      #- CORS=http://localhost:3000,http://localhost:3001
      - CORS=all
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
      #- MAX_IMPORT_CACHE_SIZE=100000 # Number of items cached during import of past history
      #- TIMEZONE=Europe/Paris # Only affects read requests, write are in UTC time
  mongo:
    container_name: mongo2
    image: mongo
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: web2
    restart: always
    ports:
      - "3300:3300"
    environment:
      - API_ENDPOINT=https://spotifybackend.duckdns.org
```

![image](https://user-images.githubusercontent.com/69928057/155899797-e63af450-6164-4087-b050-33d07b4244fb.png)

**Comment by Yooooomi** [comment]
Ok, do not modify the internal port of the client container, keep it 3300:3000.
Can you post your caddy config again?

**Comment by the-citizenfour** [comment]
Ok, I've redeployed it with the 3000 Port.

Caddyfile:
```
marcspotify.duckdns.org:443 {
    reverse_proxy localhost:3000
}
spotifybackend.duckdns.org:443 {
    reverse_proxy localhost:11224
}
```

**Comment by Yooooomi** [comment]
And this is still not working? Can you show me the browser url?

**Comment by the-citizenfour** [comment]
Yes it's still giving me the error.

Sure: https://marcspotify.duckdns.org for the frontend and https://spotifybackend.duckdns.org for the backend

**Comment by Yooooomi** [comment]
If I go to your installation I can see this
<img width="488" alt="image" src="https://user-images.githubusercontent.com/17204739/155900651-a05fa1d4-8e58-4903-a404-a0e77025a954.png">

It means the API_ENDPOINT is not set correctly in the docker-compose file, make sure you recreate the containers.

**Comment by the-citizenfour** [comment]
That's my current compose:

```
version: "3"

services:
  app:
    image: yooooomi/your_spotify_server
    container_name: express-mongo2
    restart: always
    ports:
      - "11224:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotifybackend.duckdns.org # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=https://marcspotify.duckdns.org
      - SPOTIFY_PUBLIC=c65d307da7d748b8a24f946252a9d1b3
      - SPOTIFY_SECRET=***
      #- CORS=http://localhost:3000,http://localhost:3001
      - CORS=all
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
      #- MAX_IMPORT_CACHE_SIZE=100000 # Number of items cached during import of past history
      #- TIMEZONE=Europe/Paris # Only affects read requests, write are in UTC time
  mongo:
    container_name: mongo2
    image: mongo
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    container_name: web2
    restart: always
    ports:
      - "3300:3000"
    environment:
      - API_ENDPOINT=https://spotifybackend.duckdns.org
```

Shouldn't it be https://spotifybackend.duckdns.org?
