### ISSUE TITLE
Could not retrieve global preferences error

### ISSUE THREAD

**Issue by SiriusBrightstar** [Yooooomi/your_spotify#97]
Could not retrieve global preferences warning in `http://192.168.29.136:3000/login`. 

Any suggestion for changing port numbers? I have a service using 8080, I replaced 8080 to 8000 and I'm getting the same error as #85 

I'm using a Raspberry Pi 4 with Ubuntu Server 20.04 LTS

```yaml
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8000:8000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.29.136:8000 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://192.168.29.136:3000
      - SPOTIFY_PUBLIC=
      - SPOTIFY_SECRET=
      - CORS=http://192.168.29.136:3000,http://192.168.29.136:3001 # all if you want to allow every origin
      - TIMEZONE=Asia/Kolkata
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://192.168.29.136:8000
```

![image](https://user-images.githubusercontent.com/62252266/156884389-21b22473-718a-4876-b6a3-c77f35c83681.png)
